// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: destination.proto

// Package agentkms.plugin.v1 — Destination Plugin Interface
//
// This file defines the DestinationDelivererService wire protocol. It is
// intentionally in the same proto package as plugin.proto so that shared
// types (KindRequest, KindResponse, PluginInfo) can be reused without import
// cycles, and so that a single protoc invocation regenerates both files.
//
// Regenerate after editing:
//
//   protoc \
//     -I /opt/homebrew/Cellar/protobuf/34.1/include \
//     -I api/plugin/v1 \
//     --go_out=api/plugin/v1 \
//     --go_opt=paths=source_relative \
//     --go-grpc_out=api/plugin/v1 \
//     --go-grpc_opt=paths=source_relative \
//     api/plugin/v1/destination.proto
//
// Wire encoding: standard protobuf binary (proto3). Same as plugin.proto.
// Python destination plugins generated by grpc_tools.protoc speak this
// encoding natively. Do NOT reintroduce the JSON codec removed in ef5fd5a1.

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DestinationDelivererService_Kind_FullMethodName         = "/agentkms.plugin.v1.DestinationDelivererService/Kind"
	DestinationDelivererService_Capabilities_FullMethodName = "/agentkms.plugin.v1.DestinationDelivererService/Capabilities"
	DestinationDelivererService_Validate_FullMethodName     = "/agentkms.plugin.v1.DestinationDelivererService/Validate"
	DestinationDelivererService_Deliver_FullMethodName      = "/agentkms.plugin.v1.DestinationDelivererService/Deliver"
	DestinationDelivererService_Revoke_FullMethodName       = "/agentkms.plugin.v1.DestinationDelivererService/Revoke"
	DestinationDelivererService_Health_FullMethodName       = "/agentkms.plugin.v1.DestinationDelivererService/Health"
)

// DestinationDelivererServiceClient is the client API for DestinationDelivererService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DestinationDelivererService is the plugin-side credential delivery interface.
// Plugins that write credentials to consumer-side targets implement this service.
//
// Relationship to provider services:
//   - CredentialVenderService (plugin.proto) mints credentials.
//   - DestinationDelivererService (this file) delivers them to targets.
//
// Handshake: uses the same HandshakeConfig as provider plugins
// (ProtocolVersion=1, MagicCookieKey="PLUGIN_MAGIC_COOKIE",
// MagicCookieValue="agentkms_plugin_v1"). See internal/plugin/plugins.go.
//
// PluginMap key: "destination_deliverer" (add to PluginMap in plugins.go).
//
// A plugin binary may implement both provider services (plugin.proto) and
// DestinationDelivererService in the same binary. The host dispenses each
// service independently.
type DestinationDelivererServiceClient interface {
	// Kind returns the destination kind this plugin handles (e.g. "github-secret").
	// Called once at startup; the result is stored on the adapter and used
	// to register the plugin in the destination registry.
	// Mirrors KindRequest/KindResponse from plugin.proto — reuse those message types.
	Kind(ctx context.Context, in *KindRequest, opts ...grpc.CallOption) (*KindResponse, error)
	// Capabilities returns the feature set and API version this service supports.
	// Called once at startup after Kind(). Reuses CapabilitiesRequest/Response
	// from plugin.proto (same package).
	Capabilities(ctx context.Context, in *CapabilitiesRequest, opts ...grpc.CallOption) (*CapabilitiesResponse, error)
	// Validate performs a pre-flight connectivity and permission check.
	// Must not write secret material. Must complete within 10 seconds.
	// A non-OK response is treated as a permanent configuration error.
	Validate(ctx context.Context, in *ValidateDestinationRequest, opts ...grpc.CallOption) (*ValidateDestinationResponse, error)
	// Deliver writes credential_value to the target identified by target_id.
	// Idempotent: multiple calls with the same delivery_id and generation produce
	// the same observable outcome. Plugins must not create duplicate entries.
	// See spec §4.3 and §5 for the full idempotency contract.
	Deliver(ctx context.Context, in *DeliverRequest, opts ...grpc.CallOption) (*DeliverResponse, error)
	// Revoke removes the credential from the target identified by target_id.
	// Idempotent: returns DESTINATION_OK if the credential is already absent.
	// Destinations that cannot remove credentials return DESTINATION_PERMANENT
	// with a descriptive error_message — this does not block the broader
	// revocation flow (the orchestrator logs and continues).
	Revoke(ctx context.Context, in *RevokeDestinationRequest, opts ...grpc.CallOption) (*RevokeDestinationResponse, error)
	// Health verifies that the destination is reachable and the plugin's
	// service account credentials are valid. Must complete within 5 seconds.
	// Called by the host health loop every 30 seconds. Must not write data.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type destinationDelivererServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDestinationDelivererServiceClient(cc grpc.ClientConnInterface) DestinationDelivererServiceClient {
	return &destinationDelivererServiceClient{cc}
}

func (c *destinationDelivererServiceClient) Kind(ctx context.Context, in *KindRequest, opts ...grpc.CallOption) (*KindResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KindResponse)
	err := c.cc.Invoke(ctx, DestinationDelivererService_Kind_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *destinationDelivererServiceClient) Capabilities(ctx context.Context, in *CapabilitiesRequest, opts ...grpc.CallOption) (*CapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapabilitiesResponse)
	err := c.cc.Invoke(ctx, DestinationDelivererService_Capabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *destinationDelivererServiceClient) Validate(ctx context.Context, in *ValidateDestinationRequest, opts ...grpc.CallOption) (*ValidateDestinationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateDestinationResponse)
	err := c.cc.Invoke(ctx, DestinationDelivererService_Validate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *destinationDelivererServiceClient) Deliver(ctx context.Context, in *DeliverRequest, opts ...grpc.CallOption) (*DeliverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliverResponse)
	err := c.cc.Invoke(ctx, DestinationDelivererService_Deliver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *destinationDelivererServiceClient) Revoke(ctx context.Context, in *RevokeDestinationRequest, opts ...grpc.CallOption) (*RevokeDestinationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeDestinationResponse)
	err := c.cc.Invoke(ctx, DestinationDelivererService_Revoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *destinationDelivererServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, DestinationDelivererService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DestinationDelivererServiceServer is the server API for DestinationDelivererService service.
// All implementations must embed UnimplementedDestinationDelivererServiceServer
// for forward compatibility.
//
// DestinationDelivererService is the plugin-side credential delivery interface.
// Plugins that write credentials to consumer-side targets implement this service.
//
// Relationship to provider services:
//   - CredentialVenderService (plugin.proto) mints credentials.
//   - DestinationDelivererService (this file) delivers them to targets.
//
// Handshake: uses the same HandshakeConfig as provider plugins
// (ProtocolVersion=1, MagicCookieKey="PLUGIN_MAGIC_COOKIE",
// MagicCookieValue="agentkms_plugin_v1"). See internal/plugin/plugins.go.
//
// PluginMap key: "destination_deliverer" (add to PluginMap in plugins.go).
//
// A plugin binary may implement both provider services (plugin.proto) and
// DestinationDelivererService in the same binary. The host dispenses each
// service independently.
type DestinationDelivererServiceServer interface {
	// Kind returns the destination kind this plugin handles (e.g. "github-secret").
	// Called once at startup; the result is stored on the adapter and used
	// to register the plugin in the destination registry.
	// Mirrors KindRequest/KindResponse from plugin.proto — reuse those message types.
	Kind(context.Context, *KindRequest) (*KindResponse, error)
	// Capabilities returns the feature set and API version this service supports.
	// Called once at startup after Kind(). Reuses CapabilitiesRequest/Response
	// from plugin.proto (same package).
	Capabilities(context.Context, *CapabilitiesRequest) (*CapabilitiesResponse, error)
	// Validate performs a pre-flight connectivity and permission check.
	// Must not write secret material. Must complete within 10 seconds.
	// A non-OK response is treated as a permanent configuration error.
	Validate(context.Context, *ValidateDestinationRequest) (*ValidateDestinationResponse, error)
	// Deliver writes credential_value to the target identified by target_id.
	// Idempotent: multiple calls with the same delivery_id and generation produce
	// the same observable outcome. Plugins must not create duplicate entries.
	// See spec §4.3 and §5 for the full idempotency contract.
	Deliver(context.Context, *DeliverRequest) (*DeliverResponse, error)
	// Revoke removes the credential from the target identified by target_id.
	// Idempotent: returns DESTINATION_OK if the credential is already absent.
	// Destinations that cannot remove credentials return DESTINATION_PERMANENT
	// with a descriptive error_message — this does not block the broader
	// revocation flow (the orchestrator logs and continues).
	Revoke(context.Context, *RevokeDestinationRequest) (*RevokeDestinationResponse, error)
	// Health verifies that the destination is reachable and the plugin's
	// service account credentials are valid. Must complete within 5 seconds.
	// Called by the host health loop every 30 seconds. Must not write data.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedDestinationDelivererServiceServer()
}

// UnimplementedDestinationDelivererServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDestinationDelivererServiceServer struct{}

func (UnimplementedDestinationDelivererServiceServer) Kind(context.Context, *KindRequest) (*KindResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Kind not implemented")
}
func (UnimplementedDestinationDelivererServiceServer) Capabilities(context.Context, *CapabilitiesRequest) (*CapabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Capabilities not implemented")
}
func (UnimplementedDestinationDelivererServiceServer) Validate(context.Context, *ValidateDestinationRequest) (*ValidateDestinationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Validate not implemented")
}
func (UnimplementedDestinationDelivererServiceServer) Deliver(context.Context, *DeliverRequest) (*DeliverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Deliver not implemented")
}
func (UnimplementedDestinationDelivererServiceServer) Revoke(context.Context, *RevokeDestinationRequest) (*RevokeDestinationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Revoke not implemented")
}
func (UnimplementedDestinationDelivererServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedDestinationDelivererServiceServer) mustEmbedUnimplementedDestinationDelivererServiceServer() {
}
func (UnimplementedDestinationDelivererServiceServer) testEmbeddedByValue() {}

// UnsafeDestinationDelivererServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DestinationDelivererServiceServer will
// result in compilation errors.
type UnsafeDestinationDelivererServiceServer interface {
	mustEmbedUnimplementedDestinationDelivererServiceServer()
}

func RegisterDestinationDelivererServiceServer(s grpc.ServiceRegistrar, srv DestinationDelivererServiceServer) {
	// If the following call panics, it indicates UnimplementedDestinationDelivererServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DestinationDelivererService_ServiceDesc, srv)
}

func _DestinationDelivererService_Kind_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DestinationDelivererServiceServer).Kind(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DestinationDelivererService_Kind_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DestinationDelivererServiceServer).Kind(ctx, req.(*KindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DestinationDelivererService_Capabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DestinationDelivererServiceServer).Capabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DestinationDelivererService_Capabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DestinationDelivererServiceServer).Capabilities(ctx, req.(*CapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DestinationDelivererService_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateDestinationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DestinationDelivererServiceServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DestinationDelivererService_Validate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DestinationDelivererServiceServer).Validate(ctx, req.(*ValidateDestinationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DestinationDelivererService_Deliver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DestinationDelivererServiceServer).Deliver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DestinationDelivererService_Deliver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DestinationDelivererServiceServer).Deliver(ctx, req.(*DeliverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DestinationDelivererService_Revoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeDestinationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DestinationDelivererServiceServer).Revoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DestinationDelivererService_Revoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DestinationDelivererServiceServer).Revoke(ctx, req.(*RevokeDestinationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DestinationDelivererService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DestinationDelivererServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DestinationDelivererService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DestinationDelivererServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DestinationDelivererService_ServiceDesc is the grpc.ServiceDesc for DestinationDelivererService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DestinationDelivererService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentkms.plugin.v1.DestinationDelivererService",
	HandlerType: (*DestinationDelivererServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Kind",
			Handler:    _DestinationDelivererService_Kind_Handler,
		},
		{
			MethodName: "Capabilities",
			Handler:    _DestinationDelivererService_Capabilities_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _DestinationDelivererService_Validate_Handler,
		},
		{
			MethodName: "Deliver",
			Handler:    _DestinationDelivererService_Deliver_Handler,
		},
		{
			MethodName: "Revoke",
			Handler:    _DestinationDelivererService_Revoke_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _DestinationDelivererService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "destination.proto",
}
