// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: destination.proto

// Package agentkms.plugin.v1 — Destination Plugin Interface
//
// This file defines the DestinationDelivererService wire protocol. It is
// intentionally in the same proto package as plugin.proto so that shared
// types (KindRequest, KindResponse, PluginInfo) can be reused without import
// cycles, and so that a single protoc invocation regenerates both files.
//
// Regenerate after editing:
//
//   protoc \
//     -I /opt/homebrew/Cellar/protobuf/34.1/include \
//     -I api/plugin/v1 \
//     --go_out=api/plugin/v1 \
//     --go_opt=paths=source_relative \
//     --go-grpc_out=api/plugin/v1 \
//     --go-grpc_opt=paths=source_relative \
//     api/plugin/v1/destination.proto
//
// Wire encoding: standard protobuf binary (proto3). Same as plugin.proto.
// Python destination plugins generated by grpc_tools.protoc speak this
// encoding natively. Do NOT reintroduce the JSON codec removed in ef5fd5a1.

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DestinationErrorCode classifies delivery and revocation errors so the
// orchestrator can make retry decisions without parsing error strings.
//
// This enum is new in the destination interface. It is not retrofitted into
// plugin.proto's existing *Response messages (that is a separate decision for
// the coordinator — see OQ-5 in the spec doc).
type DestinationErrorCode int32

const (
	// DESTINATION_ERROR_UNSPECIFIED must not appear in real responses.
	// A plugin that returns this code is violating the contract.
	DestinationErrorCode_DESTINATION_ERROR_UNSPECIFIED DestinationErrorCode = 0
	// DESTINATION_OK indicates success. error_message must be empty.
	DestinationErrorCode_DESTINATION_OK DestinationErrorCode = 1
	// DESTINATION_TRANSIENT indicates a failure the orchestrator should retry
	// (network timeout, rate limit, temporary service unavailability).
	DestinationErrorCode_DESTINATION_TRANSIENT DestinationErrorCode = 2
	// DESTINATION_PERMANENT indicates a failure requiring operator intervention
	// (target does not exist, insufficient permissions, unsupported operation).
	DestinationErrorCode_DESTINATION_PERMANENT DestinationErrorCode = 3
	// DESTINATION_GENERATION_REGRESSION is returned when the request's
	// generation is less than the last successfully delivered generation.
	// This is always a permanent error — the orchestrator must not retry.
	DestinationErrorCode_DESTINATION_GENERATION_REGRESSION DestinationErrorCode = 4
	// DESTINATION_TARGET_NOT_FOUND means target_id does not identify a known
	// resource at the destination (e.g. repository not found, namespace missing).
	// Always permanent.
	DestinationErrorCode_DESTINATION_TARGET_NOT_FOUND DestinationErrorCode = 5
	// DESTINATION_PERMISSION_DENIED means the plugin's service account lacks
	// write access to the target. Always permanent.
	DestinationErrorCode_DESTINATION_PERMISSION_DENIED DestinationErrorCode = 6
)

// Enum value maps for DestinationErrorCode.
var (
	DestinationErrorCode_name = map[int32]string{
		0: "DESTINATION_ERROR_UNSPECIFIED",
		1: "DESTINATION_OK",
		2: "DESTINATION_TRANSIENT",
		3: "DESTINATION_PERMANENT",
		4: "DESTINATION_GENERATION_REGRESSION",
		5: "DESTINATION_TARGET_NOT_FOUND",
		6: "DESTINATION_PERMISSION_DENIED",
	}
	DestinationErrorCode_value = map[string]int32{
		"DESTINATION_ERROR_UNSPECIFIED":     0,
		"DESTINATION_OK":                    1,
		"DESTINATION_TRANSIENT":             2,
		"DESTINATION_PERMANENT":             3,
		"DESTINATION_GENERATION_REGRESSION": 4,
		"DESTINATION_TARGET_NOT_FOUND":      5,
		"DESTINATION_PERMISSION_DENIED":     6,
	}
)

func (x DestinationErrorCode) Enum() *DestinationErrorCode {
	p := new(DestinationErrorCode)
	*p = x
	return p
}

func (x DestinationErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DestinationErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_destination_proto_enumTypes[0].Descriptor()
}

func (DestinationErrorCode) Type() protoreflect.EnumType {
	return &file_destination_proto_enumTypes[0]
}

func (x DestinationErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DestinationErrorCode.Descriptor instead.
func (DestinationErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_destination_proto_rawDescGZIP(), []int{0}
}

// ValidateDestinationRequest is the input to DestinationDelivererService.Validate.
// No credential value is passed — this is a pre-flight connectivity and
// permission check only.
type ValidateDestinationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// params holds kind-specific destination configuration (e.g. GitHub token,
	// k8s kubeconfig context, Vault address). Shape defined by each plugin kind.
	// Must not contain any secret values from the credential being delivered.
	Params        *structpb.Struct `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateDestinationRequest) Reset() {
	*x = ValidateDestinationRequest{}
	mi := &file_destination_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateDestinationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateDestinationRequest) ProtoMessage() {}

func (x *ValidateDestinationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_destination_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateDestinationRequest.ProtoReflect.Descriptor instead.
func (*ValidateDestinationRequest) Descriptor() ([]byte, []int) {
	return file_destination_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateDestinationRequest) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

// ValidateDestinationResponse is the output of DestinationDelivererService.Validate.
// A failed Validate is always treated as a permanent configuration error by the
// orchestrator — there is no is_transient field here.
type ValidateDestinationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// error_code classifies the failure. DESTINATION_OK on success.
	ErrorCode DestinationErrorCode `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=agentkms.plugin.v1.DestinationErrorCode" json:"error_code,omitempty"`
	// error_message is a human-readable description of the failure. Empty on success.
	// Must not contain secret material (params values, credential bytes).
	ErrorMessage  string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateDestinationResponse) Reset() {
	*x = ValidateDestinationResponse{}
	mi := &file_destination_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateDestinationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateDestinationResponse) ProtoMessage() {}

func (x *ValidateDestinationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_destination_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateDestinationResponse.ProtoReflect.Descriptor instead.
func (*ValidateDestinationResponse) Descriptor() ([]byte, []int) {
	return file_destination_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateDestinationResponse) GetErrorCode() DestinationErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return DestinationErrorCode_DESTINATION_ERROR_UNSPECIFIED
}

func (x *ValidateDestinationResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// DeliverRequest is the input to DestinationDelivererService.Deliver.
type DeliverRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// target_id is the opaque, kind-scoped identifier for the specific secret
	// slot at the destination.
	//
	// Format is defined per plugin kind (see spec §7.3). Examples:
	//
	//	"owner/repo:SECRET_NAME"          — github-secret
	//	"namespace/secret-name:key"       — k8s-secret
	//	"/etc/envs/prod.env:API_KEY"      — env-file
	//	"secret/data/myapp:api_key"       — vault-kv
	//	"myservice.service:MY_CRED"       — systemd-creds
	//
	// The orchestrator treats this field as opaque. Plugins must not rely on
	// the orchestrator parsing or validating the format.
	TargetId string `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	// credential_value is the raw credential bytes to write to the target.
	// SECURITY: Plugins must not log this field. Zero the buffer after use
	// where the runtime allows it.
	CredentialValue []byte `protobuf:"bytes,2,opt,name=credential_value,json=credentialValue,proto3" json:"credential_value,omitempty"`
	// generation is a monotonically increasing rotation counter assigned by
	// the orchestrator. Starts at 1 for the first delivery of a credential;
	// increments by 1 on each rotation.
	//
	// Plugins must reject requests where generation < last_delivered_generation
	// with DESTINATION_GENERATION_REGRESSION.
	Generation uint64 `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`
	// delivery_id is a UUID v4 assigned by the orchestrator for this rotation
	// event (not this individual RPC call). Retries of the same rotation carry
	// the same delivery_id so plugins can detect and de-duplicate retry calls.
	DeliveryId string `protobuf:"bytes,4,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	// ttl_seconds is the credential's expected lifetime from issuance, in seconds.
	// Informational hint only. Destinations that support secret expiry metadata
	// may use this to configure TTL at the target; others ignore it.
	TtlSeconds int64 `protobuf:"varint,5,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	// expires_at is the wall-clock expiry of the credential.
	// Informational hint. Same semantics as ttl_seconds.
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// requester_id is the stable identity string of the entity that triggered
	// this vend (from mTLS cert CN or AgentKMS identity token).
	// Write to destination-side metadata where supported; used for attribution.
	// Must be treated as a label/annotation, not secret material.
	RequesterId string `protobuf:"bytes,7,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	// credential_uuid is the UUID of the VendedCredential this delivery
	// corresponds to. Used by the orchestrator for audit correlation between
	// the vend event and the delivery event.
	CredentialUuid string `protobuf:"bytes,8,opt,name=credential_uuid,json=credentialUuid,proto3" json:"credential_uuid,omitempty"`
	// params holds kind-specific delivery parameters.
	// Shape is defined per plugin kind. Examples:
	//
	//	github-secret: {"visibility": "selected", "selected_repository_ids": [...]}
	//	k8s-secret:    {"secret_type": "Opaque"}
	//	vault-kv:      {"mount": "secret", "cas_required": true}
	Params        *structpb.Struct `protobuf:"bytes,9,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverRequest) Reset() {
	*x = DeliverRequest{}
	mi := &file_destination_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverRequest) ProtoMessage() {}

func (x *DeliverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_destination_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverRequest.ProtoReflect.Descriptor instead.
func (*DeliverRequest) Descriptor() ([]byte, []int) {
	return file_destination_proto_rawDescGZIP(), []int{2}
}

func (x *DeliverRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *DeliverRequest) GetCredentialValue() []byte {
	if x != nil {
		return x.CredentialValue
	}
	return nil
}

func (x *DeliverRequest) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *DeliverRequest) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *DeliverRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *DeliverRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *DeliverRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

func (x *DeliverRequest) GetCredentialUuid() string {
	if x != nil {
		return x.CredentialUuid
	}
	return ""
}

func (x *DeliverRequest) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

// DeliverResponse is the output of DestinationDelivererService.Deliver.
type DeliverResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// error_code classifies the result. DESTINATION_OK on success.
	ErrorCode DestinationErrorCode `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=agentkms.plugin.v1.DestinationErrorCode" json:"error_code,omitempty"`
	// error_message is a human-readable description of the failure. Empty on success.
	// Must not contain credential_value bytes.
	ErrorMessage  string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverResponse) Reset() {
	*x = DeliverResponse{}
	mi := &file_destination_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverResponse) ProtoMessage() {}

func (x *DeliverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_destination_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverResponse.ProtoReflect.Descriptor instead.
func (*DeliverResponse) Descriptor() ([]byte, []int) {
	return file_destination_proto_rawDescGZIP(), []int{3}
}

func (x *DeliverResponse) GetErrorCode() DestinationErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return DestinationErrorCode_DESTINATION_ERROR_UNSPECIFIED
}

func (x *DeliverResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// RevokeDestinationRequest is the input to DestinationDelivererService.Revoke.
type RevokeDestinationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// target_id identifies the secret slot to remove. Same format as DeliverRequest.
	TargetId string `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	// credential_uuid is the UUID of the credential being decommissioned.
	// Used for audit correlation.
	CredentialUuid string `protobuf:"bytes,2,opt,name=credential_uuid,json=credentialUuid,proto3" json:"credential_uuid,omitempty"`
	// generation is the generation number of the credential being revoked.
	// Plugins may use this to verify they are revoking the expected version
	// rather than a newer credential written by a concurrent rotation.
	Generation uint64 `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`
	// params holds kind-specific parameters needed to reach the target.
	// Same shape as DeliverRequest.params for the same kind.
	Params        *structpb.Struct `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeDestinationRequest) Reset() {
	*x = RevokeDestinationRequest{}
	mi := &file_destination_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeDestinationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeDestinationRequest) ProtoMessage() {}

func (x *RevokeDestinationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_destination_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeDestinationRequest.ProtoReflect.Descriptor instead.
func (*RevokeDestinationRequest) Descriptor() ([]byte, []int) {
	return file_destination_proto_rawDescGZIP(), []int{4}
}

func (x *RevokeDestinationRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *RevokeDestinationRequest) GetCredentialUuid() string {
	if x != nil {
		return x.CredentialUuid
	}
	return ""
}

func (x *RevokeDestinationRequest) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *RevokeDestinationRequest) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

// RevokeDestinationResponse is the output of DestinationDelivererService.Revoke.
type RevokeDestinationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// error_code classifies the result. DESTINATION_OK on success (including
	// the case where the credential was already absent — Revoke is idempotent).
	ErrorCode DestinationErrorCode `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=agentkms.plugin.v1.DestinationErrorCode" json:"error_code,omitempty"`
	// error_message is a human-readable description of the failure. Empty on success.
	ErrorMessage  string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeDestinationResponse) Reset() {
	*x = RevokeDestinationResponse{}
	mi := &file_destination_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeDestinationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeDestinationResponse) ProtoMessage() {}

func (x *RevokeDestinationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_destination_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeDestinationResponse.ProtoReflect.Descriptor instead.
func (*RevokeDestinationResponse) Descriptor() ([]byte, []int) {
	return file_destination_proto_rawDescGZIP(), []int{5}
}

func (x *RevokeDestinationResponse) GetErrorCode() DestinationErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return DestinationErrorCode_DESTINATION_ERROR_UNSPECIFIED
}

func (x *RevokeDestinationResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// HealthRequest is intentionally empty, mirroring KindRequest.
// The host does not need to pass context to the plugin for a health check;
// connectivity is the plugin's sole concern.
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_destination_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_destination_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_destination_proto_rawDescGZIP(), []int{6}
}

// HealthResponse is the output of DestinationDelivererService.Health.
type HealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// error_code is DESTINATION_OK when the destination is reachable and
	// the plugin's credentials are valid. Any other value means unhealthy.
	ErrorCode DestinationErrorCode `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=agentkms.plugin.v1.DestinationErrorCode" json:"error_code,omitempty"`
	// error_message describes the health failure. Empty when healthy.
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// latency_ms is the round-trip time of the connectivity probe in milliseconds.
	// Optional (zero if not measured). Used for observability dashboards.
	LatencyMs     int64 `protobuf:"varint,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_destination_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_destination_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_destination_proto_rawDescGZIP(), []int{7}
}

func (x *HealthResponse) GetErrorCode() DestinationErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return DestinationErrorCode_DESTINATION_ERROR_UNSPECIFIED
}

func (x *HealthResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *HealthResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

var File_destination_proto protoreflect.FileDescriptor

const file_destination_proto_rawDesc = "" +
	"\n" +
	"\x11destination.proto\x12\x12agentkms.plugin.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fplugin.proto\"M\n" +
	"\x1aValidateDestinationRequest\x12/\n" +
	"\x06params\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x06params\"\x8b\x01\n" +
	"\x1bValidateDestinationResponse\x12G\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2(.agentkms.plugin.v1.DestinationErrorCodeR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\xf2\x02\n" +
	"\x0eDeliverRequest\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\x12)\n" +
	"\x10credential_value\x18\x02 \x01(\fR\x0fcredentialValue\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\x04R\n" +
	"generation\x12\x1f\n" +
	"\vdelivery_id\x18\x04 \x01(\tR\n" +
	"deliveryId\x12\x1f\n" +
	"\vttl_seconds\x18\x05 \x01(\x03R\n" +
	"ttlSeconds\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12!\n" +
	"\frequester_id\x18\a \x01(\tR\vrequesterId\x12'\n" +
	"\x0fcredential_uuid\x18\b \x01(\tR\x0ecredentialUuid\x12/\n" +
	"\x06params\x18\t \x01(\v2\x17.google.protobuf.StructR\x06params\"\x7f\n" +
	"\x0fDeliverResponse\x12G\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2(.agentkms.plugin.v1.DestinationErrorCodeR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\xb1\x01\n" +
	"\x18RevokeDestinationRequest\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\x12'\n" +
	"\x0fcredential_uuid\x18\x02 \x01(\tR\x0ecredentialUuid\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\x04R\n" +
	"generation\x12/\n" +
	"\x06params\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x06params\"\x89\x01\n" +
	"\x19RevokeDestinationResponse\x12G\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2(.agentkms.plugin.v1.DestinationErrorCodeR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x0f\n" +
	"\rHealthRequest\"\x9d\x01\n" +
	"\x0eHealthResponse\x12G\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2(.agentkms.plugin.v1.DestinationErrorCodeR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x03 \x01(\x03R\tlatencyMs*\xef\x01\n" +
	"\x14DestinationErrorCode\x12!\n" +
	"\x1dDESTINATION_ERROR_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eDESTINATION_OK\x10\x01\x12\x19\n" +
	"\x15DESTINATION_TRANSIENT\x10\x02\x12\x19\n" +
	"\x15DESTINATION_PERMANENT\x10\x03\x12%\n" +
	"!DESTINATION_GENERATION_REGRESSION\x10\x04\x12 \n" +
	"\x1cDESTINATION_TARGET_NOT_FOUND\x10\x05\x12!\n" +
	"\x1dDESTINATION_PERMISSION_DENIED\x10\x062\xc4\x04\n" +
	"\x1bDestinationDelivererService\x12I\n" +
	"\x04Kind\x12\x1f.agentkms.plugin.v1.KindRequest\x1a .agentkms.plugin.v1.KindResponse\x12a\n" +
	"\fCapabilities\x12'.agentkms.plugin.v1.CapabilitiesRequest\x1a(.agentkms.plugin.v1.CapabilitiesResponse\x12k\n" +
	"\bValidate\x12..agentkms.plugin.v1.ValidateDestinationRequest\x1a/.agentkms.plugin.v1.ValidateDestinationResponse\x12R\n" +
	"\aDeliver\x12\".agentkms.plugin.v1.DeliverRequest\x1a#.agentkms.plugin.v1.DeliverResponse\x12e\n" +
	"\x06Revoke\x12,.agentkms.plugin.v1.RevokeDestinationRequest\x1a-.agentkms.plugin.v1.RevokeDestinationResponse\x12O\n" +
	"\x06Health\x12!.agentkms.plugin.v1.HealthRequest\x1a\".agentkms.plugin.v1.HealthResponseB5Z3github.com/agentkms/agentkms/api/plugin/v1;pluginv1b\x06proto3"

var (
	file_destination_proto_rawDescOnce sync.Once
	file_destination_proto_rawDescData []byte
)

func file_destination_proto_rawDescGZIP() []byte {
	file_destination_proto_rawDescOnce.Do(func() {
		file_destination_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_destination_proto_rawDesc), len(file_destination_proto_rawDesc)))
	})
	return file_destination_proto_rawDescData
}

var file_destination_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_destination_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_destination_proto_goTypes = []any{
	(DestinationErrorCode)(0),           // 0: agentkms.plugin.v1.DestinationErrorCode
	(*ValidateDestinationRequest)(nil),  // 1: agentkms.plugin.v1.ValidateDestinationRequest
	(*ValidateDestinationResponse)(nil), // 2: agentkms.plugin.v1.ValidateDestinationResponse
	(*DeliverRequest)(nil),              // 3: agentkms.plugin.v1.DeliverRequest
	(*DeliverResponse)(nil),             // 4: agentkms.plugin.v1.DeliverResponse
	(*RevokeDestinationRequest)(nil),    // 5: agentkms.plugin.v1.RevokeDestinationRequest
	(*RevokeDestinationResponse)(nil),   // 6: agentkms.plugin.v1.RevokeDestinationResponse
	(*HealthRequest)(nil),               // 7: agentkms.plugin.v1.HealthRequest
	(*HealthResponse)(nil),              // 8: agentkms.plugin.v1.HealthResponse
	(*structpb.Struct)(nil),             // 9: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),       // 10: google.protobuf.Timestamp
	(*KindRequest)(nil),                 // 11: agentkms.plugin.v1.KindRequest
	(*CapabilitiesRequest)(nil),         // 12: agentkms.plugin.v1.CapabilitiesRequest
	(*KindResponse)(nil),                // 13: agentkms.plugin.v1.KindResponse
	(*CapabilitiesResponse)(nil),        // 14: agentkms.plugin.v1.CapabilitiesResponse
}
var file_destination_proto_depIdxs = []int32{
	9,  // 0: agentkms.plugin.v1.ValidateDestinationRequest.params:type_name -> google.protobuf.Struct
	0,  // 1: agentkms.plugin.v1.ValidateDestinationResponse.error_code:type_name -> agentkms.plugin.v1.DestinationErrorCode
	10, // 2: agentkms.plugin.v1.DeliverRequest.expires_at:type_name -> google.protobuf.Timestamp
	9,  // 3: agentkms.plugin.v1.DeliverRequest.params:type_name -> google.protobuf.Struct
	0,  // 4: agentkms.plugin.v1.DeliverResponse.error_code:type_name -> agentkms.plugin.v1.DestinationErrorCode
	9,  // 5: agentkms.plugin.v1.RevokeDestinationRequest.params:type_name -> google.protobuf.Struct
	0,  // 6: agentkms.plugin.v1.RevokeDestinationResponse.error_code:type_name -> agentkms.plugin.v1.DestinationErrorCode
	0,  // 7: agentkms.plugin.v1.HealthResponse.error_code:type_name -> agentkms.plugin.v1.DestinationErrorCode
	11, // 8: agentkms.plugin.v1.DestinationDelivererService.Kind:input_type -> agentkms.plugin.v1.KindRequest
	12, // 9: agentkms.plugin.v1.DestinationDelivererService.Capabilities:input_type -> agentkms.plugin.v1.CapabilitiesRequest
	1,  // 10: agentkms.plugin.v1.DestinationDelivererService.Validate:input_type -> agentkms.plugin.v1.ValidateDestinationRequest
	3,  // 11: agentkms.plugin.v1.DestinationDelivererService.Deliver:input_type -> agentkms.plugin.v1.DeliverRequest
	5,  // 12: agentkms.plugin.v1.DestinationDelivererService.Revoke:input_type -> agentkms.plugin.v1.RevokeDestinationRequest
	7,  // 13: agentkms.plugin.v1.DestinationDelivererService.Health:input_type -> agentkms.plugin.v1.HealthRequest
	13, // 14: agentkms.plugin.v1.DestinationDelivererService.Kind:output_type -> agentkms.plugin.v1.KindResponse
	14, // 15: agentkms.plugin.v1.DestinationDelivererService.Capabilities:output_type -> agentkms.plugin.v1.CapabilitiesResponse
	2,  // 16: agentkms.plugin.v1.DestinationDelivererService.Validate:output_type -> agentkms.plugin.v1.ValidateDestinationResponse
	4,  // 17: agentkms.plugin.v1.DestinationDelivererService.Deliver:output_type -> agentkms.plugin.v1.DeliverResponse
	6,  // 18: agentkms.plugin.v1.DestinationDelivererService.Revoke:output_type -> agentkms.plugin.v1.RevokeDestinationResponse
	8,  // 19: agentkms.plugin.v1.DestinationDelivererService.Health:output_type -> agentkms.plugin.v1.HealthResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_destination_proto_init() }
func file_destination_proto_init() {
	if File_destination_proto != nil {
		return
	}
	file_plugin_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_destination_proto_rawDesc), len(file_destination_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_destination_proto_goTypes,
		DependencyIndexes: file_destination_proto_depIdxs,
		EnumInfos:         file_destination_proto_enumTypes,
		MessageInfos:      file_destination_proto_msgTypes,
	}.Build()
	File_destination_proto = out.File
	file_destination_proto_goTypes = nil
	file_destination_proto_depIdxs = nil
}
