// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: host.proto

// Package agentkms.plugin.v1 — Host Callback Service (HostService)
//
// This file defines the HostService wire protocol. HostService is served by
// the OSS host process and consumed by the Pro rotation orchestrator plugin.
// It is the callback half of the bidirectional gRPC pattern described in
// docs/specs/2026-04-26-T5-host-callback-design.md.
//
// Only "rotation_orchestrator" plugins receive a HostService handle.
// Provider plugins and destination plugins are NOT affected by this file.
//
// Transport: the host uses go-plugin's GRPCBroker to open a side channel
// within the existing plugin subprocess pair. The broker ID is passed to the
// plugin during Init. The plugin dials back and obtains a HostServiceClient
// before returning from Init. See internal/plugin/host_service.go for the
// server implementation and agentkms-pro/internal/host/client.go for the
// consumer.
//
// Regenerate Go bindings after editing:
//
//   protoc \
//     -I /opt/homebrew/Cellar/protobuf/34.1/include \
//     -I api/plugin/v1 \
//     --go_out=api/plugin/v1 \
//     --go_opt=paths=source_relative \
//     --go-grpc_out=api/plugin/v1 \
//     --go-grpc_opt=paths=source_relative \
//     api/plugin/v1/host.proto
//
// Wire encoding: standard protobuf binary (proto3). Same as plugin.proto and
// destination.proto. Do NOT introduce JSON codec.

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HostService_ListBindings_FullMethodName            = "/agentkms.plugin.v1.HostService/ListBindings"
	HostService_GetBinding_FullMethodName              = "/agentkms.plugin.v1.HostService/GetBinding"
	HostService_SaveBindingMetadata_FullMethodName     = "/agentkms.plugin.v1.HostService/SaveBindingMetadata"
	HostService_VendCredential_FullMethodName          = "/agentkms.plugin.v1.HostService/VendCredential"
	HostService_DeliverToDestination_FullMethodName    = "/agentkms.plugin.v1.HostService/DeliverToDestination"
	HostService_RevokeAtDestination_FullMethodName     = "/agentkms.plugin.v1.HostService/RevokeAtDestination"
	HostService_RevokeCredential_FullMethodName        = "/agentkms.plugin.v1.HostService/RevokeCredential"
	HostService_EmitAudit_FullMethodName               = "/agentkms.plugin.v1.HostService/EmitAudit"
	HostService_EnqueueRevocation_FullMethodName       = "/agentkms.plugin.v1.HostService/EnqueueRevocation"
	HostService_DrainPendingRevocations_FullMethodName = "/agentkms.plugin.v1.HostService/DrainPendingRevocations"
	HostService_AckRevocation_FullMethodName           = "/agentkms.plugin.v1.HostService/AckRevocation"
)

// HostServiceClient is the client API for HostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HostService is the callback service served by the OSS host and consumed by
// the Pro rotation orchestrator plugin. It gives the plugin subprocess
// controlled access to OSS-internal state: binding store, provider registry,
// destination registry, audit chain, and the pending-revocation queue.
//
// Transport: go-plugin GRPCBroker side channel within the established plugin
// process pair. The host calls broker.AcceptAndServe(brokerID, server) during
// orchestrator plugin startup; the plugin calls broker.Dial(brokerID) to
// obtain a *grpc.ClientConn and construct a HostServiceClient.
//
// Authentication: the gRPC connection is gated by the existing go-plugin
// handshake cookie and Ed25519 plugin binary signature verification (see
// internal/plugin/signing.go). No additional TLS or token authentication is
// needed at the HostService gRPC level.
//
// Scope: HostService is registered only for plugins dispensed under the
// PluginMap key "rotation_orchestrator". Provider and destination plugins
// (scope_validator, credential_vender, destination_deliverer) do not receive
// a broker ID and cannot reach this service.
//
// Concurrency: see docs/specs/2026-04-26-T5-host-callback-design.md §4 for
// the full concurrency contract. Short summary:
//   - VendCredential, DeliverToDestination, RevokeAtDestination: parallel calls safe.
//   - SaveBindingMetadata for the same binding name: serialized by the host.
//   - EnqueueRevocation / DrainPendingRevocations / AckRevocation: linearizable.
type HostServiceClient interface {
	// ListBindings returns a paginated list of bindings matching the filter.
	// Idempotent (read-only). Safe to call in parallel.
	// Error semantics: HOST_TRANSIENT if the KV layer is temporarily unavailable.
	ListBindings(ctx context.Context, in *ListBindingsRequest, opts ...grpc.CallOption) (*BindingList, error)
	// GetBinding fetches a specific binding by name.
	// Idempotent (read-only).
	// Error semantics: HOST_NOT_FOUND if no binding with that name exists.
	GetBinding(ctx context.Context, in *GetBindingRequest, opts ...grpc.CallOption) (*GetBindingResponse, error)
	// SaveBindingMetadata persists the metadata fields the orchestrator owns
	// after a rotation (LastGeneration, LastRotatedAt, BindingState,
	// LastCredentialUUID). It does NOT replace the full binding — only these
	// four fields. Concurrent calls for the same binding name are serialized
	// by the host using the binding store's write mutex.
	//
	// Idempotency: calling with the same patch twice is safe; the second call
	// produces no observable change (generation check prevents regression).
	//
	// Error semantics:
	//
	//	HOST_NOT_FOUND    — binding name does not exist.
	//	HOST_PERMANENT    — patch.last_generation < current LastGeneration
	//	                    (generation regression rejected).
	//	HOST_TRANSIENT    — KV layer temporarily unavailable.
	SaveBindingMetadata(ctx context.Context, in *SaveBindingMetadataRequest, opts ...grpc.CallOption) (*SaveBindingMetadataResponse, error)
	// VendCredential dispatches to the provider plugin identified by provider_kind.
	// The host looks up the plugin in the provider registry, calls Vend, and
	// returns the result. The orchestrator never holds provider plugin handles.
	//
	// The host does NOT automatically emit an audit event for the vend — the
	// orchestrator calls EmitAudit with the binding_rotate_start event before
	// calling VendCredential (T5 §4.2 step 2→3). The orchestrator must emit its
	// own binding_rotate audit event after this call (step 6). Open question
	// OQ-HC-4 tracks whether the host should auto-emit OperationCredentialVend
	// here to avoid double-emission concerns.
	//
	// Idempotency: NOT idempotent. Each call mints a distinct credential at the
	// provider. The orchestrator must call this at most once per rotation step.
	//
	// Error semantics:
	//
	//	HOST_NOT_FOUND    — provider_kind not registered in the host registry.
	//	HOST_TRANSIENT    — provider plugin subprocess is restarting.
	//	HOST_PERMANENT    — provider rejected the vend (bad scope, auth failure).
	VendCredential(ctx context.Context, in *VendCredentialRequest, opts ...grpc.CallOption) (*VendCredentialResponse, error)
	// DeliverToDestination dispatches to the destination plugin identified by
	// destination_kind. The host looks up the plugin in the destination registry,
	// calls Deliver, and maps the DestinationErrorCode response onto
	// HostCallbackErrorCode. The orchestrator never holds destination plugin handles.
	//
	// Idempotency: idempotent via delivery_id. Multiple calls with the same
	// delivery_id and generation produce the same observable outcome at the target
	// (per DeliverRequest.delivery_id semantics in destination.proto).
	//
	// Parallel calls for different destination_kinds are safe. Parallel calls for
	// the same destination_kind target are safe (destination plugins handle concurrency).
	//
	// Error semantics: HOST_NOT_FOUND if destination_kind not registered.
	// Other codes map from DestinationErrorCode as documented in
	// DeliverToDestinationResponse.error_code.
	DeliverToDestination(ctx context.Context, in *DeliverToDestinationRequest, opts ...grpc.CallOption) (*DeliverToDestinationResponse, error)
	// RevokeAtDestination dispatches a Revoke to the destination plugin identified
	// by destination_kind. Symmetric to DeliverToDestination.
	//
	// Idempotency: idempotent — DESTINATION_OK is returned if the credential is
	// already absent (per RevokeDestinationResponse semantics in destination.proto).
	//
	// Error semantics: destination plugins that cannot remove credentials return
	// HOST_PERMANENT; the orchestrator logs and continues (non-fatal per T5 §4.2).
	RevokeAtDestination(ctx context.Context, in *RevokeAtDestinationRequest, opts ...grpc.CallOption) (*RevokeAtDestinationResponse, error)
	// RevokeCredential revokes the credential identified by credential_uuid at
	// its provider. The host looks up the credential UUID in the audit store to
	// identify provider_kind, then dispatches to the provider plugin's Revoke RPC.
	//
	// Idempotency: idempotent. If the credential is already revoked or unknown to
	// the provider, HOST_OK is returned (non-fatal, log and continue).
	//
	// Error semantics:
	//
	//	HOST_NOT_FOUND  — credential_uuid not found in the audit store.
	//	HOST_TRANSIENT  — provider plugin subprocess is restarting.
	//	HOST_PERMANENT  — provider rejected the revocation permanently.
	//
	// Revocation failure is non-fatal for the rotation as a whole (T5 §4.2 step 7).
	// The orchestrator logs "old_credential_revoke_failed" anomaly and continues.
	RevokeCredential(ctx context.Context, in *RevokeCredentialRequest, opts ...grpc.CallOption) (*RevokeCredentialResponse, error)
	// EmitAudit writes an audit event through the OSS Auditor. This is required
	// because the orchestrator's audit chain must share the same write path as
	// the OSS-side audit so forensics queries see one unified stream. The host
	// maps AuditEventProto onto audit.AuditEvent, calls AuditEvent.Validate(),
	// and passes it to the configured Auditor.Log.
	//
	// Idempotency: NOT idempotent. Each call writes a distinct event with a new
	// host-generated EventID. The orchestrator must not call this twice for the
	// same logical event.
	//
	// Error semantics:
	//
	//	HOST_PERMANENT  — AuditEvent.Validate() failed (key material in free-text
	//	                  field, invalid InvalidationReason, etc.).
	//	HOST_TRANSIENT  — audit sink temporarily unavailable.
	//
	// Ordering: the orchestrator must call EmitAudit for binding_rotate_start
	// BEFORE calling VendCredential (T5 §4.2 step 2→3). The host does not
	// enforce ordering — it is the orchestrator's responsibility.
	EmitAudit(ctx context.Context, in *EmitAuditRequest, opts ...grpc.CallOption) (*EmitAuditResponse, error)
	// EnqueueRevocation persists a delayed-revocation entry to EncryptedKV under
	// "orchestrator/pending-revocations/<credential_uuid>". Called by the orchestrator
	// at T5 §4.2 step 7 when GracePeriodSeconds > 0.
	//
	// Idempotency: idempotent. Enqueueing the same credential_uuid twice is safe;
	// the host upserts the entry (later scheduled_at wins, so re-enqueue can delay).
	//
	// Linearizability: EnqueueRevocation and DrainPendingRevocations are
	// serialized by the host using the KV store's write mutex. A credential
	// enqueued before a DrainPendingRevocations call with now >= scheduled_at
	// is guaranteed to appear in the drain response.
	//
	// Error semantics: HOST_TRANSIENT if KV layer is temporarily unavailable.
	EnqueueRevocation(ctx context.Context, in *EnqueueRevocationRequest, opts ...grpc.CallOption) (*EnqueueRevocationResponse, error)
	// DrainPendingRevocations returns all pending revocations whose scheduled_at
	// is <= the provided now timestamp. Called by the orchestrator on startup and
	// periodically (recommended: every 60 seconds) to find due revocations.
	//
	// Idempotency: idempotent. Returning the same entry twice is safe — the
	// orchestrator's RevokeCredential call is idempotent, and AckRevocation
	// removes the entry after successful revocation.
	//
	// Error semantics: HOST_TRANSIENT if KV layer is temporarily unavailable.
	DrainPendingRevocations(ctx context.Context, in *DrainPendingRevocationsRequest, opts ...grpc.CallOption) (*DrainPendingRevocationsResponse, error)
	// AckRevocation signals that the orchestrator successfully revoked the
	// credential and the host should remove the pending-revocation entry from
	// EncryptedKV.
	//
	// Idempotency: idempotent. Acking an already-removed credential_uuid returns
	// HOST_OK (not HOST_NOT_FOUND) — the desired state (entry removed) is already met.
	//
	// Error semantics: HOST_TRANSIENT if KV layer is temporarily unavailable.
	AckRevocation(ctx context.Context, in *AckRevocationRequest, opts ...grpc.CallOption) (*AckRevocationResponse, error)
}

type hostServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHostServiceClient(cc grpc.ClientConnInterface) HostServiceClient {
	return &hostServiceClient{cc}
}

func (c *hostServiceClient) ListBindings(ctx context.Context, in *ListBindingsRequest, opts ...grpc.CallOption) (*BindingList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BindingList)
	err := c.cc.Invoke(ctx, HostService_ListBindings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) GetBinding(ctx context.Context, in *GetBindingRequest, opts ...grpc.CallOption) (*GetBindingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBindingResponse)
	err := c.cc.Invoke(ctx, HostService_GetBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) SaveBindingMetadata(ctx context.Context, in *SaveBindingMetadataRequest, opts ...grpc.CallOption) (*SaveBindingMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveBindingMetadataResponse)
	err := c.cc.Invoke(ctx, HostService_SaveBindingMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) VendCredential(ctx context.Context, in *VendCredentialRequest, opts ...grpc.CallOption) (*VendCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VendCredentialResponse)
	err := c.cc.Invoke(ctx, HostService_VendCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) DeliverToDestination(ctx context.Context, in *DeliverToDestinationRequest, opts ...grpc.CallOption) (*DeliverToDestinationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliverToDestinationResponse)
	err := c.cc.Invoke(ctx, HostService_DeliverToDestination_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) RevokeAtDestination(ctx context.Context, in *RevokeAtDestinationRequest, opts ...grpc.CallOption) (*RevokeAtDestinationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeAtDestinationResponse)
	err := c.cc.Invoke(ctx, HostService_RevokeAtDestination_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) RevokeCredential(ctx context.Context, in *RevokeCredentialRequest, opts ...grpc.CallOption) (*RevokeCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeCredentialResponse)
	err := c.cc.Invoke(ctx, HostService_RevokeCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) EmitAudit(ctx context.Context, in *EmitAuditRequest, opts ...grpc.CallOption) (*EmitAuditResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmitAuditResponse)
	err := c.cc.Invoke(ctx, HostService_EmitAudit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) EnqueueRevocation(ctx context.Context, in *EnqueueRevocationRequest, opts ...grpc.CallOption) (*EnqueueRevocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnqueueRevocationResponse)
	err := c.cc.Invoke(ctx, HostService_EnqueueRevocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) DrainPendingRevocations(ctx context.Context, in *DrainPendingRevocationsRequest, opts ...grpc.CallOption) (*DrainPendingRevocationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DrainPendingRevocationsResponse)
	err := c.cc.Invoke(ctx, HostService_DrainPendingRevocations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) AckRevocation(ctx context.Context, in *AckRevocationRequest, opts ...grpc.CallOption) (*AckRevocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckRevocationResponse)
	err := c.cc.Invoke(ctx, HostService_AckRevocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostServiceServer is the server API for HostService service.
// All implementations must embed UnimplementedHostServiceServer
// for forward compatibility.
//
// HostService is the callback service served by the OSS host and consumed by
// the Pro rotation orchestrator plugin. It gives the plugin subprocess
// controlled access to OSS-internal state: binding store, provider registry,
// destination registry, audit chain, and the pending-revocation queue.
//
// Transport: go-plugin GRPCBroker side channel within the established plugin
// process pair. The host calls broker.AcceptAndServe(brokerID, server) during
// orchestrator plugin startup; the plugin calls broker.Dial(brokerID) to
// obtain a *grpc.ClientConn and construct a HostServiceClient.
//
// Authentication: the gRPC connection is gated by the existing go-plugin
// handshake cookie and Ed25519 plugin binary signature verification (see
// internal/plugin/signing.go). No additional TLS or token authentication is
// needed at the HostService gRPC level.
//
// Scope: HostService is registered only for plugins dispensed under the
// PluginMap key "rotation_orchestrator". Provider and destination plugins
// (scope_validator, credential_vender, destination_deliverer) do not receive
// a broker ID and cannot reach this service.
//
// Concurrency: see docs/specs/2026-04-26-T5-host-callback-design.md §4 for
// the full concurrency contract. Short summary:
//   - VendCredential, DeliverToDestination, RevokeAtDestination: parallel calls safe.
//   - SaveBindingMetadata for the same binding name: serialized by the host.
//   - EnqueueRevocation / DrainPendingRevocations / AckRevocation: linearizable.
type HostServiceServer interface {
	// ListBindings returns a paginated list of bindings matching the filter.
	// Idempotent (read-only). Safe to call in parallel.
	// Error semantics: HOST_TRANSIENT if the KV layer is temporarily unavailable.
	ListBindings(context.Context, *ListBindingsRequest) (*BindingList, error)
	// GetBinding fetches a specific binding by name.
	// Idempotent (read-only).
	// Error semantics: HOST_NOT_FOUND if no binding with that name exists.
	GetBinding(context.Context, *GetBindingRequest) (*GetBindingResponse, error)
	// SaveBindingMetadata persists the metadata fields the orchestrator owns
	// after a rotation (LastGeneration, LastRotatedAt, BindingState,
	// LastCredentialUUID). It does NOT replace the full binding — only these
	// four fields. Concurrent calls for the same binding name are serialized
	// by the host using the binding store's write mutex.
	//
	// Idempotency: calling with the same patch twice is safe; the second call
	// produces no observable change (generation check prevents regression).
	//
	// Error semantics:
	//
	//	HOST_NOT_FOUND    — binding name does not exist.
	//	HOST_PERMANENT    — patch.last_generation < current LastGeneration
	//	                    (generation regression rejected).
	//	HOST_TRANSIENT    — KV layer temporarily unavailable.
	SaveBindingMetadata(context.Context, *SaveBindingMetadataRequest) (*SaveBindingMetadataResponse, error)
	// VendCredential dispatches to the provider plugin identified by provider_kind.
	// The host looks up the plugin in the provider registry, calls Vend, and
	// returns the result. The orchestrator never holds provider plugin handles.
	//
	// The host does NOT automatically emit an audit event for the vend — the
	// orchestrator calls EmitAudit with the binding_rotate_start event before
	// calling VendCredential (T5 §4.2 step 2→3). The orchestrator must emit its
	// own binding_rotate audit event after this call (step 6). Open question
	// OQ-HC-4 tracks whether the host should auto-emit OperationCredentialVend
	// here to avoid double-emission concerns.
	//
	// Idempotency: NOT idempotent. Each call mints a distinct credential at the
	// provider. The orchestrator must call this at most once per rotation step.
	//
	// Error semantics:
	//
	//	HOST_NOT_FOUND    — provider_kind not registered in the host registry.
	//	HOST_TRANSIENT    — provider plugin subprocess is restarting.
	//	HOST_PERMANENT    — provider rejected the vend (bad scope, auth failure).
	VendCredential(context.Context, *VendCredentialRequest) (*VendCredentialResponse, error)
	// DeliverToDestination dispatches to the destination plugin identified by
	// destination_kind. The host looks up the plugin in the destination registry,
	// calls Deliver, and maps the DestinationErrorCode response onto
	// HostCallbackErrorCode. The orchestrator never holds destination plugin handles.
	//
	// Idempotency: idempotent via delivery_id. Multiple calls with the same
	// delivery_id and generation produce the same observable outcome at the target
	// (per DeliverRequest.delivery_id semantics in destination.proto).
	//
	// Parallel calls for different destination_kinds are safe. Parallel calls for
	// the same destination_kind target are safe (destination plugins handle concurrency).
	//
	// Error semantics: HOST_NOT_FOUND if destination_kind not registered.
	// Other codes map from DestinationErrorCode as documented in
	// DeliverToDestinationResponse.error_code.
	DeliverToDestination(context.Context, *DeliverToDestinationRequest) (*DeliverToDestinationResponse, error)
	// RevokeAtDestination dispatches a Revoke to the destination plugin identified
	// by destination_kind. Symmetric to DeliverToDestination.
	//
	// Idempotency: idempotent — DESTINATION_OK is returned if the credential is
	// already absent (per RevokeDestinationResponse semantics in destination.proto).
	//
	// Error semantics: destination plugins that cannot remove credentials return
	// HOST_PERMANENT; the orchestrator logs and continues (non-fatal per T5 §4.2).
	RevokeAtDestination(context.Context, *RevokeAtDestinationRequest) (*RevokeAtDestinationResponse, error)
	// RevokeCredential revokes the credential identified by credential_uuid at
	// its provider. The host looks up the credential UUID in the audit store to
	// identify provider_kind, then dispatches to the provider plugin's Revoke RPC.
	//
	// Idempotency: idempotent. If the credential is already revoked or unknown to
	// the provider, HOST_OK is returned (non-fatal, log and continue).
	//
	// Error semantics:
	//
	//	HOST_NOT_FOUND  — credential_uuid not found in the audit store.
	//	HOST_TRANSIENT  — provider plugin subprocess is restarting.
	//	HOST_PERMANENT  — provider rejected the revocation permanently.
	//
	// Revocation failure is non-fatal for the rotation as a whole (T5 §4.2 step 7).
	// The orchestrator logs "old_credential_revoke_failed" anomaly and continues.
	RevokeCredential(context.Context, *RevokeCredentialRequest) (*RevokeCredentialResponse, error)
	// EmitAudit writes an audit event through the OSS Auditor. This is required
	// because the orchestrator's audit chain must share the same write path as
	// the OSS-side audit so forensics queries see one unified stream. The host
	// maps AuditEventProto onto audit.AuditEvent, calls AuditEvent.Validate(),
	// and passes it to the configured Auditor.Log.
	//
	// Idempotency: NOT idempotent. Each call writes a distinct event with a new
	// host-generated EventID. The orchestrator must not call this twice for the
	// same logical event.
	//
	// Error semantics:
	//
	//	HOST_PERMANENT  — AuditEvent.Validate() failed (key material in free-text
	//	                  field, invalid InvalidationReason, etc.).
	//	HOST_TRANSIENT  — audit sink temporarily unavailable.
	//
	// Ordering: the orchestrator must call EmitAudit for binding_rotate_start
	// BEFORE calling VendCredential (T5 §4.2 step 2→3). The host does not
	// enforce ordering — it is the orchestrator's responsibility.
	EmitAudit(context.Context, *EmitAuditRequest) (*EmitAuditResponse, error)
	// EnqueueRevocation persists a delayed-revocation entry to EncryptedKV under
	// "orchestrator/pending-revocations/<credential_uuid>". Called by the orchestrator
	// at T5 §4.2 step 7 when GracePeriodSeconds > 0.
	//
	// Idempotency: idempotent. Enqueueing the same credential_uuid twice is safe;
	// the host upserts the entry (later scheduled_at wins, so re-enqueue can delay).
	//
	// Linearizability: EnqueueRevocation and DrainPendingRevocations are
	// serialized by the host using the KV store's write mutex. A credential
	// enqueued before a DrainPendingRevocations call with now >= scheduled_at
	// is guaranteed to appear in the drain response.
	//
	// Error semantics: HOST_TRANSIENT if KV layer is temporarily unavailable.
	EnqueueRevocation(context.Context, *EnqueueRevocationRequest) (*EnqueueRevocationResponse, error)
	// DrainPendingRevocations returns all pending revocations whose scheduled_at
	// is <= the provided now timestamp. Called by the orchestrator on startup and
	// periodically (recommended: every 60 seconds) to find due revocations.
	//
	// Idempotency: idempotent. Returning the same entry twice is safe — the
	// orchestrator's RevokeCredential call is idempotent, and AckRevocation
	// removes the entry after successful revocation.
	//
	// Error semantics: HOST_TRANSIENT if KV layer is temporarily unavailable.
	DrainPendingRevocations(context.Context, *DrainPendingRevocationsRequest) (*DrainPendingRevocationsResponse, error)
	// AckRevocation signals that the orchestrator successfully revoked the
	// credential and the host should remove the pending-revocation entry from
	// EncryptedKV.
	//
	// Idempotency: idempotent. Acking an already-removed credential_uuid returns
	// HOST_OK (not HOST_NOT_FOUND) — the desired state (entry removed) is already met.
	//
	// Error semantics: HOST_TRANSIENT if KV layer is temporarily unavailable.
	AckRevocation(context.Context, *AckRevocationRequest) (*AckRevocationResponse, error)
	mustEmbedUnimplementedHostServiceServer()
}

// UnimplementedHostServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostServiceServer struct{}

func (UnimplementedHostServiceServer) ListBindings(context.Context, *ListBindingsRequest) (*BindingList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBindings not implemented")
}
func (UnimplementedHostServiceServer) GetBinding(context.Context, *GetBindingRequest) (*GetBindingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBinding not implemented")
}
func (UnimplementedHostServiceServer) SaveBindingMetadata(context.Context, *SaveBindingMetadataRequest) (*SaveBindingMetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveBindingMetadata not implemented")
}
func (UnimplementedHostServiceServer) VendCredential(context.Context, *VendCredentialRequest) (*VendCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VendCredential not implemented")
}
func (UnimplementedHostServiceServer) DeliverToDestination(context.Context, *DeliverToDestinationRequest) (*DeliverToDestinationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeliverToDestination not implemented")
}
func (UnimplementedHostServiceServer) RevokeAtDestination(context.Context, *RevokeAtDestinationRequest) (*RevokeAtDestinationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeAtDestination not implemented")
}
func (UnimplementedHostServiceServer) RevokeCredential(context.Context, *RevokeCredentialRequest) (*RevokeCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeCredential not implemented")
}
func (UnimplementedHostServiceServer) EmitAudit(context.Context, *EmitAuditRequest) (*EmitAuditResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EmitAudit not implemented")
}
func (UnimplementedHostServiceServer) EnqueueRevocation(context.Context, *EnqueueRevocationRequest) (*EnqueueRevocationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnqueueRevocation not implemented")
}
func (UnimplementedHostServiceServer) DrainPendingRevocations(context.Context, *DrainPendingRevocationsRequest) (*DrainPendingRevocationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DrainPendingRevocations not implemented")
}
func (UnimplementedHostServiceServer) AckRevocation(context.Context, *AckRevocationRequest) (*AckRevocationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AckRevocation not implemented")
}
func (UnimplementedHostServiceServer) mustEmbedUnimplementedHostServiceServer() {}
func (UnimplementedHostServiceServer) testEmbeddedByValue()                     {}

// UnsafeHostServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostServiceServer will
// result in compilation errors.
type UnsafeHostServiceServer interface {
	mustEmbedUnimplementedHostServiceServer()
}

func RegisterHostServiceServer(s grpc.ServiceRegistrar, srv HostServiceServer) {
	// If the following call panics, it indicates UnimplementedHostServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HostService_ServiceDesc, srv)
}

func _HostService_ListBindings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBindingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).ListBindings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_ListBindings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).ListBindings(ctx, req.(*ListBindingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_GetBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).GetBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_GetBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).GetBinding(ctx, req.(*GetBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_SaveBindingMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveBindingMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).SaveBindingMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_SaveBindingMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).SaveBindingMetadata(ctx, req.(*SaveBindingMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_VendCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VendCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).VendCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_VendCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).VendCredential(ctx, req.(*VendCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_DeliverToDestination_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliverToDestinationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).DeliverToDestination(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_DeliverToDestination_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).DeliverToDestination(ctx, req.(*DeliverToDestinationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_RevokeAtDestination_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeAtDestinationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).RevokeAtDestination(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_RevokeAtDestination_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).RevokeAtDestination(ctx, req.(*RevokeAtDestinationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_RevokeCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).RevokeCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_RevokeCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).RevokeCredential(ctx, req.(*RevokeCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_EmitAudit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmitAuditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).EmitAudit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_EmitAudit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).EmitAudit(ctx, req.(*EmitAuditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_EnqueueRevocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnqueueRevocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).EnqueueRevocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_EnqueueRevocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).EnqueueRevocation(ctx, req.(*EnqueueRevocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_DrainPendingRevocations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrainPendingRevocationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).DrainPendingRevocations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_DrainPendingRevocations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).DrainPendingRevocations(ctx, req.(*DrainPendingRevocationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_AckRevocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckRevocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).AckRevocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_AckRevocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).AckRevocation(ctx, req.(*AckRevocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HostService_ServiceDesc is the grpc.ServiceDesc for HostService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentkms.plugin.v1.HostService",
	HandlerType: (*HostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListBindings",
			Handler:    _HostService_ListBindings_Handler,
		},
		{
			MethodName: "GetBinding",
			Handler:    _HostService_GetBinding_Handler,
		},
		{
			MethodName: "SaveBindingMetadata",
			Handler:    _HostService_SaveBindingMetadata_Handler,
		},
		{
			MethodName: "VendCredential",
			Handler:    _HostService_VendCredential_Handler,
		},
		{
			MethodName: "DeliverToDestination",
			Handler:    _HostService_DeliverToDestination_Handler,
		},
		{
			MethodName: "RevokeAtDestination",
			Handler:    _HostService_RevokeAtDestination_Handler,
		},
		{
			MethodName: "RevokeCredential",
			Handler:    _HostService_RevokeCredential_Handler,
		},
		{
			MethodName: "EmitAudit",
			Handler:    _HostService_EmitAudit_Handler,
		},
		{
			MethodName: "EnqueueRevocation",
			Handler:    _HostService_EnqueueRevocation_Handler,
		},
		{
			MethodName: "DrainPendingRevocations",
			Handler:    _HostService_DrainPendingRevocations_Handler,
		},
		{
			MethodName: "AckRevocation",
			Handler:    _HostService_AckRevocation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "host.proto",
}

const (
	OrchestratorService_Ping_FullMethodName                 = "/agentkms.plugin.v1.OrchestratorService/Ping"
	OrchestratorService_Init_FullMethodName                 = "/agentkms.plugin.v1.OrchestratorService/Init"
	OrchestratorService_TriggerRotation_FullMethodName      = "/agentkms.plugin.v1.OrchestratorService/TriggerRotation"
	OrchestratorService_BindingForCredential_FullMethodName = "/agentkms.plugin.v1.OrchestratorService/BindingForCredential"
)

// OrchestratorServiceClient is the client API for OrchestratorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OrchestratorService is implemented by the Pro orchestrator plugin and
// consumed by the OSS host. The OSS PluginMap entry "rotation_orchestrator"
// maps to this service on the GRPCClient side.
type OrchestratorServiceClient interface {
	// Ping is the host's liveness probe. Called before Init (to confirm the
	// plugin subprocess is responsive) and periodically after Init (every 30s
	// in the orchestratorHealthLoop). Returns HOST_OK when the plugin is healthy.
	// Deliberately does not depend on Init having completed so the host can
	// probe early-startup liveness.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// Init performs the plugin startup handshake. The host calls Init after
	// dispensing the plugin, passing the host_broker_id so the plugin can
	// connect to HostService. The plugin verifies its license, dials the broker,
	// starts the cron driver, and returns. If Init returns a non-empty
	// error_message the host does not register the RotationHook and the plugin
	// subprocess is killed.
	Init(ctx context.Context, in *OrchestratorInitRequest, opts ...grpc.CallOption) (*OrchestratorInitResponse, error)
	// TriggerRotation initiates an emergency rotation for the credential
	// identified by credential_uuid. Returns immediately; rotation proceeds
	// asynchronously. Implements the webhooks.RotationHook.TriggerRotation contract.
	TriggerRotation(ctx context.Context, in *TriggerRotationRequest, opts ...grpc.CallOption) (*TriggerRotationResponse, error)
	// BindingForCredential returns the binding name associated with a given
	// credentialUUID, or not_found=true if the credential is not managed by any
	// binding. Implements the webhooks.RotationHook.BindingForCredential contract.
	BindingForCredential(ctx context.Context, in *BindingForCredentialRequest, opts ...grpc.CallOption) (*BindingForCredentialResponse, error)
}

type orchestratorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestratorServiceClient(cc grpc.ClientConnInterface) OrchestratorServiceClient {
	return &orchestratorServiceClient{cc}
}

func (c *orchestratorServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) Init(ctx context.Context, in *OrchestratorInitRequest, opts ...grpc.CallOption) (*OrchestratorInitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrchestratorInitResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_Init_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) TriggerRotation(ctx context.Context, in *TriggerRotationRequest, opts ...grpc.CallOption) (*TriggerRotationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerRotationResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_TriggerRotation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) BindingForCredential(ctx context.Context, in *BindingForCredentialRequest, opts ...grpc.CallOption) (*BindingForCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BindingForCredentialResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_BindingForCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrchestratorServiceServer is the server API for OrchestratorService service.
// All implementations must embed UnimplementedOrchestratorServiceServer
// for forward compatibility.
//
// OrchestratorService is implemented by the Pro orchestrator plugin and
// consumed by the OSS host. The OSS PluginMap entry "rotation_orchestrator"
// maps to this service on the GRPCClient side.
type OrchestratorServiceServer interface {
	// Ping is the host's liveness probe. Called before Init (to confirm the
	// plugin subprocess is responsive) and periodically after Init (every 30s
	// in the orchestratorHealthLoop). Returns HOST_OK when the plugin is healthy.
	// Deliberately does not depend on Init having completed so the host can
	// probe early-startup liveness.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// Init performs the plugin startup handshake. The host calls Init after
	// dispensing the plugin, passing the host_broker_id so the plugin can
	// connect to HostService. The plugin verifies its license, dials the broker,
	// starts the cron driver, and returns. If Init returns a non-empty
	// error_message the host does not register the RotationHook and the plugin
	// subprocess is killed.
	Init(context.Context, *OrchestratorInitRequest) (*OrchestratorInitResponse, error)
	// TriggerRotation initiates an emergency rotation for the credential
	// identified by credential_uuid. Returns immediately; rotation proceeds
	// asynchronously. Implements the webhooks.RotationHook.TriggerRotation contract.
	TriggerRotation(context.Context, *TriggerRotationRequest) (*TriggerRotationResponse, error)
	// BindingForCredential returns the binding name associated with a given
	// credentialUUID, or not_found=true if the credential is not managed by any
	// binding. Implements the webhooks.RotationHook.BindingForCredential contract.
	BindingForCredential(context.Context, *BindingForCredentialRequest) (*BindingForCredentialResponse, error)
	mustEmbedUnimplementedOrchestratorServiceServer()
}

// UnimplementedOrchestratorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrchestratorServiceServer struct{}

func (UnimplementedOrchestratorServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedOrchestratorServiceServer) Init(context.Context, *OrchestratorInitRequest) (*OrchestratorInitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedOrchestratorServiceServer) TriggerRotation(context.Context, *TriggerRotationRequest) (*TriggerRotationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerRotation not implemented")
}
func (UnimplementedOrchestratorServiceServer) BindingForCredential(context.Context, *BindingForCredentialRequest) (*BindingForCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BindingForCredential not implemented")
}
func (UnimplementedOrchestratorServiceServer) mustEmbedUnimplementedOrchestratorServiceServer() {}
func (UnimplementedOrchestratorServiceServer) testEmbeddedByValue()                             {}

// UnsafeOrchestratorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrchestratorServiceServer will
// result in compilation errors.
type UnsafeOrchestratorServiceServer interface {
	mustEmbedUnimplementedOrchestratorServiceServer()
}

func RegisterOrchestratorServiceServer(s grpc.ServiceRegistrar, srv OrchestratorServiceServer) {
	// If the following call panics, it indicates UnimplementedOrchestratorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrchestratorService_ServiceDesc, srv)
}

func _OrchestratorService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrchestratorInitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_Init_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).Init(ctx, req.(*OrchestratorInitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_TriggerRotation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerRotationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).TriggerRotation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_TriggerRotation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).TriggerRotation(ctx, req.(*TriggerRotationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_BindingForCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindingForCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).BindingForCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_BindingForCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).BindingForCredential(ctx, req.(*BindingForCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrchestratorService_ServiceDesc is the grpc.ServiceDesc for OrchestratorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrchestratorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentkms.plugin.v1.OrchestratorService",
	HandlerType: (*OrchestratorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _OrchestratorService_Ping_Handler,
		},
		{
			MethodName: "Init",
			Handler:    _OrchestratorService_Init_Handler,
		},
		{
			MethodName: "TriggerRotation",
			Handler:    _OrchestratorService_TriggerRotation_Handler,
		},
		{
			MethodName: "BindingForCredential",
			Handler:    _OrchestratorService_BindingForCredential_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "host.proto",
}
