// Package pluginv1 provides the gRPC message types and service definitions
// for the AgentKMS plugin protocol.
//
// Code is generated from api/plugin/v1/plugin.proto by protoc. Do NOT edit
// the generated files (plugin.pb.go, plugin_grpc.pb.go) by hand.
//
// To regenerate after changing plugin.proto:
//
//	protoc \
//	  -I /opt/homebrew/Cellar/protobuf/34.1/include \
//	  -I api/plugin/v1 \
//	  --go_out=api/plugin/v1 \
//	  --go_opt=paths=source_relative \
//	  --go-grpc_out=api/plugin/v1 \
//	  --go-grpc_opt=paths=source_relative \
//	  api/plugin/v1/plugin.proto
//
// Build-time dependencies (not runtime):
//   - protoc          — brew install protobuf
//   - protoc-gen-go   — go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
//   - protoc-gen-go-grpc — go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
//
// Wire encoding: standard protobuf binary (proto3). Python plugins using
// grpc_tools.protoc-generated stubs speak this encoding natively — no Python-side
// changes are required to interoperate with the Go host.
//
// Previous implementation note: this file previously contained a hand-written
// jsonCodec that overrode gRPC's default "proto" codec with JSON encoding so that
// plain Go structs could be transmitted without protoc-generated code. That codec
// was removed because it broke Python interop — Python plugins generated by
// grpc_tools.protoc use standard protobuf binary encoding. The custom JSON codec
// was an expedient shortcut that violated the core "zero Python-side changes"
// promise documented in Blog Part 7.
package pluginv1

import "fmt"

// ErrFromResponse converts an RPC error field to a Go error, or nil on success.
// Kept for API stability — call sites in grpcadapter.go use the internal
// errFromField helper instead, which is identical.
func ErrFromResponse(errStr string) error {
	if errStr == "" {
		return nil
	}
	return fmt.Errorf("%s", errStr)
}
