// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: plugin.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScopeValidatorService_Kind_FullMethodName     = "/agentkms.plugin.v1.ScopeValidatorService/Kind"
	ScopeValidatorService_Validate_FullMethodName = "/agentkms.plugin.v1.ScopeValidatorService/Validate"
	ScopeValidatorService_Narrow_FullMethodName   = "/agentkms.plugin.v1.ScopeValidatorService/Narrow"
)

// ScopeValidatorServiceClient is the client API for ScopeValidatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ScopeValidatorService mirrors the ScopeValidator Go interface.
// Validates structural correctness and performs policy narrowing
// for a specific scope Kind.  Required per-Kind plugin.
type ScopeValidatorServiceClient interface {
	// Kind returns the scope Kind this plugin handles.
	Kind(ctx context.Context, in *KindRequest, opts ...grpc.CallOption) (*KindResponse, error)
	// Validate checks that the scope has a well-formed Params shape
	// for this Kind.  Must not mutate the scope.
	Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error)
	// Narrow intersects a requested Scope with policy bounds and returns
	// the effective Scope.  Returns an error if bounds are incompatible
	// with the request.
	Narrow(ctx context.Context, in *NarrowRequest, opts ...grpc.CallOption) (*NarrowResponse, error)
}

type scopeValidatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScopeValidatorServiceClient(cc grpc.ClientConnInterface) ScopeValidatorServiceClient {
	return &scopeValidatorServiceClient{cc}
}

func (c *scopeValidatorServiceClient) Kind(ctx context.Context, in *KindRequest, opts ...grpc.CallOption) (*KindResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KindResponse)
	err := c.cc.Invoke(ctx, ScopeValidatorService_Kind_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scopeValidatorServiceClient) Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateResponse)
	err := c.cc.Invoke(ctx, ScopeValidatorService_Validate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scopeValidatorServiceClient) Narrow(ctx context.Context, in *NarrowRequest, opts ...grpc.CallOption) (*NarrowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NarrowResponse)
	err := c.cc.Invoke(ctx, ScopeValidatorService_Narrow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScopeValidatorServiceServer is the server API for ScopeValidatorService service.
// All implementations must embed UnimplementedScopeValidatorServiceServer
// for forward compatibility.
//
// ScopeValidatorService mirrors the ScopeValidator Go interface.
// Validates structural correctness and performs policy narrowing
// for a specific scope Kind.  Required per-Kind plugin.
type ScopeValidatorServiceServer interface {
	// Kind returns the scope Kind this plugin handles.
	Kind(context.Context, *KindRequest) (*KindResponse, error)
	// Validate checks that the scope has a well-formed Params shape
	// for this Kind.  Must not mutate the scope.
	Validate(context.Context, *ValidateRequest) (*ValidateResponse, error)
	// Narrow intersects a requested Scope with policy bounds and returns
	// the effective Scope.  Returns an error if bounds are incompatible
	// with the request.
	Narrow(context.Context, *NarrowRequest) (*NarrowResponse, error)
	mustEmbedUnimplementedScopeValidatorServiceServer()
}

// UnimplementedScopeValidatorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScopeValidatorServiceServer struct{}

func (UnimplementedScopeValidatorServiceServer) Kind(context.Context, *KindRequest) (*KindResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Kind not implemented")
}
func (UnimplementedScopeValidatorServiceServer) Validate(context.Context, *ValidateRequest) (*ValidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Validate not implemented")
}
func (UnimplementedScopeValidatorServiceServer) Narrow(context.Context, *NarrowRequest) (*NarrowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Narrow not implemented")
}
func (UnimplementedScopeValidatorServiceServer) mustEmbedUnimplementedScopeValidatorServiceServer() {}
func (UnimplementedScopeValidatorServiceServer) testEmbeddedByValue()                               {}

// UnsafeScopeValidatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScopeValidatorServiceServer will
// result in compilation errors.
type UnsafeScopeValidatorServiceServer interface {
	mustEmbedUnimplementedScopeValidatorServiceServer()
}

func RegisterScopeValidatorServiceServer(s grpc.ServiceRegistrar, srv ScopeValidatorServiceServer) {
	// If the following call panics, it indicates UnimplementedScopeValidatorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScopeValidatorService_ServiceDesc, srv)
}

func _ScopeValidatorService_Kind_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScopeValidatorServiceServer).Kind(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScopeValidatorService_Kind_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScopeValidatorServiceServer).Kind(ctx, req.(*KindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScopeValidatorService_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScopeValidatorServiceServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScopeValidatorService_Validate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScopeValidatorServiceServer).Validate(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScopeValidatorService_Narrow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NarrowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScopeValidatorServiceServer).Narrow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScopeValidatorService_Narrow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScopeValidatorServiceServer).Narrow(ctx, req.(*NarrowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScopeValidatorService_ServiceDesc is the grpc.ServiceDesc for ScopeValidatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScopeValidatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentkms.plugin.v1.ScopeValidatorService",
	HandlerType: (*ScopeValidatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Kind",
			Handler:    _ScopeValidatorService_Kind_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _ScopeValidatorService_Validate_Handler,
		},
		{
			MethodName: "Narrow",
			Handler:    _ScopeValidatorService_Narrow_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}

const (
	ScopeAnalyzerService_Kind_FullMethodName    = "/agentkms.plugin.v1.ScopeAnalyzerService/Kind"
	ScopeAnalyzerService_Analyze_FullMethodName = "/agentkms.plugin.v1.ScopeAnalyzerService/Analyze"
)

// ScopeAnalyzerServiceClient is the client API for ScopeAnalyzerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ScopeAnalyzerService mirrors the ScopeAnalyzer Go interface.
// Assesses risk at vend time.  Optional per-Kind plugin.
// Anomalies are recorded in the audit log but do not block vending.
type ScopeAnalyzerServiceClient interface {
	// Kind returns the scope Kind this plugin handles.
	Kind(ctx context.Context, in *KindRequest, opts ...grpc.CallOption) (*KindResponse, error)
	// Analyze returns anomalies describing risky scope aspects.
	// An empty list means no risk signals were detected.
	Analyze(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error)
}

type scopeAnalyzerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScopeAnalyzerServiceClient(cc grpc.ClientConnInterface) ScopeAnalyzerServiceClient {
	return &scopeAnalyzerServiceClient{cc}
}

func (c *scopeAnalyzerServiceClient) Kind(ctx context.Context, in *KindRequest, opts ...grpc.CallOption) (*KindResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KindResponse)
	err := c.cc.Invoke(ctx, ScopeAnalyzerService_Kind_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scopeAnalyzerServiceClient) Analyze(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeResponse)
	err := c.cc.Invoke(ctx, ScopeAnalyzerService_Analyze_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScopeAnalyzerServiceServer is the server API for ScopeAnalyzerService service.
// All implementations must embed UnimplementedScopeAnalyzerServiceServer
// for forward compatibility.
//
// ScopeAnalyzerService mirrors the ScopeAnalyzer Go interface.
// Assesses risk at vend time.  Optional per-Kind plugin.
// Anomalies are recorded in the audit log but do not block vending.
type ScopeAnalyzerServiceServer interface {
	// Kind returns the scope Kind this plugin handles.
	Kind(context.Context, *KindRequest) (*KindResponse, error)
	// Analyze returns anomalies describing risky scope aspects.
	// An empty list means no risk signals were detected.
	Analyze(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error)
	mustEmbedUnimplementedScopeAnalyzerServiceServer()
}

// UnimplementedScopeAnalyzerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScopeAnalyzerServiceServer struct{}

func (UnimplementedScopeAnalyzerServiceServer) Kind(context.Context, *KindRequest) (*KindResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Kind not implemented")
}
func (UnimplementedScopeAnalyzerServiceServer) Analyze(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Analyze not implemented")
}
func (UnimplementedScopeAnalyzerServiceServer) mustEmbedUnimplementedScopeAnalyzerServiceServer() {}
func (UnimplementedScopeAnalyzerServiceServer) testEmbeddedByValue()                              {}

// UnsafeScopeAnalyzerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScopeAnalyzerServiceServer will
// result in compilation errors.
type UnsafeScopeAnalyzerServiceServer interface {
	mustEmbedUnimplementedScopeAnalyzerServiceServer()
}

func RegisterScopeAnalyzerServiceServer(s grpc.ServiceRegistrar, srv ScopeAnalyzerServiceServer) {
	// If the following call panics, it indicates UnimplementedScopeAnalyzerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScopeAnalyzerService_ServiceDesc, srv)
}

func _ScopeAnalyzerService_Kind_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScopeAnalyzerServiceServer).Kind(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScopeAnalyzerService_Kind_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScopeAnalyzerServiceServer).Kind(ctx, req.(*KindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScopeAnalyzerService_Analyze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScopeAnalyzerServiceServer).Analyze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScopeAnalyzerService_Analyze_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScopeAnalyzerServiceServer).Analyze(ctx, req.(*AnalyzeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScopeAnalyzerService_ServiceDesc is the grpc.ServiceDesc for ScopeAnalyzerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScopeAnalyzerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentkms.plugin.v1.ScopeAnalyzerService",
	HandlerType: (*ScopeAnalyzerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Kind",
			Handler:    _ScopeAnalyzerService_Kind_Handler,
		},
		{
			MethodName: "Analyze",
			Handler:    _ScopeAnalyzerService_Analyze_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}

const (
	ScopeSerializerService_Kind_FullMethodName      = "/agentkms.plugin.v1.ScopeSerializerService/Kind"
	ScopeSerializerService_Serialize_FullMethodName = "/agentkms.plugin.v1.ScopeSerializerService/Serialize"
)

// ScopeSerializerServiceClient is the client API for ScopeSerializerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ScopeSerializerService mirrors the ScopeSerializer Go interface.
// Converts a Scope to the provider-native request format.
// Required per-Kind that vends real upstream credentials.
type ScopeSerializerServiceClient interface {
	// Kind returns the scope Kind this plugin handles.
	Kind(ctx context.Context, in *KindRequest, opts ...grpc.CallOption) (*KindResponse, error)
	// Serialize converts the scope to the provider-native format
	// (AWS IAM policy document, GitHub permissions object, etc.).
	Serialize(ctx context.Context, in *SerializeRequest, opts ...grpc.CallOption) (*SerializeResponse, error)
}

type scopeSerializerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScopeSerializerServiceClient(cc grpc.ClientConnInterface) ScopeSerializerServiceClient {
	return &scopeSerializerServiceClient{cc}
}

func (c *scopeSerializerServiceClient) Kind(ctx context.Context, in *KindRequest, opts ...grpc.CallOption) (*KindResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KindResponse)
	err := c.cc.Invoke(ctx, ScopeSerializerService_Kind_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scopeSerializerServiceClient) Serialize(ctx context.Context, in *SerializeRequest, opts ...grpc.CallOption) (*SerializeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SerializeResponse)
	err := c.cc.Invoke(ctx, ScopeSerializerService_Serialize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScopeSerializerServiceServer is the server API for ScopeSerializerService service.
// All implementations must embed UnimplementedScopeSerializerServiceServer
// for forward compatibility.
//
// ScopeSerializerService mirrors the ScopeSerializer Go interface.
// Converts a Scope to the provider-native request format.
// Required per-Kind that vends real upstream credentials.
type ScopeSerializerServiceServer interface {
	// Kind returns the scope Kind this plugin handles.
	Kind(context.Context, *KindRequest) (*KindResponse, error)
	// Serialize converts the scope to the provider-native format
	// (AWS IAM policy document, GitHub permissions object, etc.).
	Serialize(context.Context, *SerializeRequest) (*SerializeResponse, error)
	mustEmbedUnimplementedScopeSerializerServiceServer()
}

// UnimplementedScopeSerializerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScopeSerializerServiceServer struct{}

func (UnimplementedScopeSerializerServiceServer) Kind(context.Context, *KindRequest) (*KindResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Kind not implemented")
}
func (UnimplementedScopeSerializerServiceServer) Serialize(context.Context, *SerializeRequest) (*SerializeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Serialize not implemented")
}
func (UnimplementedScopeSerializerServiceServer) mustEmbedUnimplementedScopeSerializerServiceServer() {
}
func (UnimplementedScopeSerializerServiceServer) testEmbeddedByValue() {}

// UnsafeScopeSerializerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScopeSerializerServiceServer will
// result in compilation errors.
type UnsafeScopeSerializerServiceServer interface {
	mustEmbedUnimplementedScopeSerializerServiceServer()
}

func RegisterScopeSerializerServiceServer(s grpc.ServiceRegistrar, srv ScopeSerializerServiceServer) {
	// If the following call panics, it indicates UnimplementedScopeSerializerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScopeSerializerService_ServiceDesc, srv)
}

func _ScopeSerializerService_Kind_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScopeSerializerServiceServer).Kind(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScopeSerializerService_Kind_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScopeSerializerServiceServer).Kind(ctx, req.(*KindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScopeSerializerService_Serialize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SerializeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScopeSerializerServiceServer).Serialize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScopeSerializerService_Serialize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScopeSerializerServiceServer).Serialize(ctx, req.(*SerializeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScopeSerializerService_ServiceDesc is the grpc.ServiceDesc for ScopeSerializerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScopeSerializerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentkms.plugin.v1.ScopeSerializerService",
	HandlerType: (*ScopeSerializerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Kind",
			Handler:    _ScopeSerializerService_Kind_Handler,
		},
		{
			MethodName: "Serialize",
			Handler:    _ScopeSerializerService_Serialize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}

const (
	CredentialVenderService_Kind_FullMethodName = "/agentkms.plugin.v1.CredentialVenderService/Kind"
	CredentialVenderService_Vend_FullMethodName = "/agentkms.plugin.v1.CredentialVenderService/Vend"
)

// CredentialVenderServiceClient is the client API for CredentialVenderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CredentialVenderService is the plugin-side credential issuance interface.
// Plugins that issue real upstream credentials implement this service.
// Mirrors the CredentialVender Go interface (not yet in core source).
type CredentialVenderServiceClient interface {
	// Kind returns the scope Kind this plugin handles.
	Kind(ctx context.Context, in *KindRequest, opts ...grpc.CallOption) (*KindResponse, error)
	// Vend issues a credential scoped to the provided Scope.
	// The returned VendedCredential holds the secret bytes, a UUID for
	// audit correlation, a hash for safe logging, and an expiry.
	Vend(ctx context.Context, in *VendRequest, opts ...grpc.CallOption) (*VendResponse, error)
}

type credentialVenderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCredentialVenderServiceClient(cc grpc.ClientConnInterface) CredentialVenderServiceClient {
	return &credentialVenderServiceClient{cc}
}

func (c *credentialVenderServiceClient) Kind(ctx context.Context, in *KindRequest, opts ...grpc.CallOption) (*KindResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KindResponse)
	err := c.cc.Invoke(ctx, CredentialVenderService_Kind_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialVenderServiceClient) Vend(ctx context.Context, in *VendRequest, opts ...grpc.CallOption) (*VendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VendResponse)
	err := c.cc.Invoke(ctx, CredentialVenderService_Vend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CredentialVenderServiceServer is the server API for CredentialVenderService service.
// All implementations must embed UnimplementedCredentialVenderServiceServer
// for forward compatibility.
//
// CredentialVenderService is the plugin-side credential issuance interface.
// Plugins that issue real upstream credentials implement this service.
// Mirrors the CredentialVender Go interface (not yet in core source).
type CredentialVenderServiceServer interface {
	// Kind returns the scope Kind this plugin handles.
	Kind(context.Context, *KindRequest) (*KindResponse, error)
	// Vend issues a credential scoped to the provided Scope.
	// The returned VendedCredential holds the secret bytes, a UUID for
	// audit correlation, a hash for safe logging, and an expiry.
	Vend(context.Context, *VendRequest) (*VendResponse, error)
	mustEmbedUnimplementedCredentialVenderServiceServer()
}

// UnimplementedCredentialVenderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCredentialVenderServiceServer struct{}

func (UnimplementedCredentialVenderServiceServer) Kind(context.Context, *KindRequest) (*KindResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Kind not implemented")
}
func (UnimplementedCredentialVenderServiceServer) Vend(context.Context, *VendRequest) (*VendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Vend not implemented")
}
func (UnimplementedCredentialVenderServiceServer) mustEmbedUnimplementedCredentialVenderServiceServer() {
}
func (UnimplementedCredentialVenderServiceServer) testEmbeddedByValue() {}

// UnsafeCredentialVenderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CredentialVenderServiceServer will
// result in compilation errors.
type UnsafeCredentialVenderServiceServer interface {
	mustEmbedUnimplementedCredentialVenderServiceServer()
}

func RegisterCredentialVenderServiceServer(s grpc.ServiceRegistrar, srv CredentialVenderServiceServer) {
	// If the following call panics, it indicates UnimplementedCredentialVenderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CredentialVenderService_ServiceDesc, srv)
}

func _CredentialVenderService_Kind_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialVenderServiceServer).Kind(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialVenderService_Kind_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialVenderServiceServer).Kind(ctx, req.(*KindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialVenderService_Vend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialVenderServiceServer).Vend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialVenderService_Vend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialVenderServiceServer).Vend(ctx, req.(*VendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CredentialVenderService_ServiceDesc is the grpc.ServiceDesc for CredentialVenderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CredentialVenderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentkms.plugin.v1.CredentialVenderService",
	HandlerType: (*CredentialVenderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Kind",
			Handler:    _CredentialVenderService_Kind_Handler,
		},
		{
			MethodName: "Vend",
			Handler:    _CredentialVenderService_Vend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}
