// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: plugin.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AnomalyLevel indicates the severity of a ScopeAnomaly.
type AnomalyLevel int32

const (
	AnomalyLevel_ANOMALY_LEVEL_UNSPECIFIED AnomalyLevel = 0
	AnomalyLevel_ANOMALY_LEVEL_INFO        AnomalyLevel = 1
	AnomalyLevel_ANOMALY_LEVEL_WARN        AnomalyLevel = 2
	AnomalyLevel_ANOMALY_LEVEL_ALERT       AnomalyLevel = 3
)

// Enum value maps for AnomalyLevel.
var (
	AnomalyLevel_name = map[int32]string{
		0: "ANOMALY_LEVEL_UNSPECIFIED",
		1: "ANOMALY_LEVEL_INFO",
		2: "ANOMALY_LEVEL_WARN",
		3: "ANOMALY_LEVEL_ALERT",
	}
	AnomalyLevel_value = map[string]int32{
		"ANOMALY_LEVEL_UNSPECIFIED": 0,
		"ANOMALY_LEVEL_INFO":        1,
		"ANOMALY_LEVEL_WARN":        2,
		"ANOMALY_LEVEL_ALERT":       3,
	}
)

func (x AnomalyLevel) Enum() *AnomalyLevel {
	p := new(AnomalyLevel)
	*p = x
	return p
}

func (x AnomalyLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnomalyLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[0].Descriptor()
}

func (AnomalyLevel) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[0]
}

func (x AnomalyLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AnomalyLevel.Descriptor instead.
func (AnomalyLevel) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

// Scope describes the effective permissions of a vended credential.
// Mirrors internal/credentials.Scope.
type Scope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kind discriminates the structural shape of params.
	// Core knows "llm-session" and "generic-vend".
	// Plugins register additional kinds (e.g. "aws-sts", "github-pat").
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Params holds Kind-specific structured scope data.
	// Shape is defined by the plugin that owns the Kind.
	// google.protobuf.Struct maps cleanly to map[string]any in Go,
	// dict in Python, serde_json::Value in Rust, etc.
	Params *structpb.Struct `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	// ttl_seconds is the effective lifetime from issuance, in seconds.
	TtlSeconds int64 `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	// issued_at is the wall-clock time the scope became valid.
	IssuedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	// expires_at is issued_at + ttl.  Stored explicitly so audit queries
	// do not have to reconstruct.
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scope) Reset() {
	*x = Scope{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scope) ProtoMessage() {}

func (x *Scope) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scope.ProtoReflect.Descriptor instead.
func (*Scope) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *Scope) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Scope) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Scope) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *Scope) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *Scope) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// ScopeBounds is the maximum scope a policy rule allows for a given
// (identity, operation) pair.  Mirrors internal/credentials.ScopeBounds.
type ScopeBounds struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kind of the scope this bounds applies to.
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// MaxParams holds the maximum allowed parameters for the scope.
	// Intersection semantics are Kind-specific and delegated to the plugin.
	MaxParams *structpb.Struct `protobuf:"bytes,2,opt,name=max_params,json=maxParams,proto3" json:"max_params,omitempty"`
	// max_ttl_seconds is the maximum allowed TTL, in seconds.
	MaxTtlSeconds int64 `protobuf:"varint,3,opt,name=max_ttl_seconds,json=maxTtlSeconds,proto3" json:"max_ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScopeBounds) Reset() {
	*x = ScopeBounds{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScopeBounds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScopeBounds) ProtoMessage() {}

func (x *ScopeBounds) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScopeBounds.ProtoReflect.Descriptor instead.
func (*ScopeBounds) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *ScopeBounds) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ScopeBounds) GetMaxParams() *structpb.Struct {
	if x != nil {
		return x.MaxParams
	}
	return nil
}

func (x *ScopeBounds) GetMaxTtlSeconds() int64 {
	if x != nil {
		return x.MaxTtlSeconds
	}
	return 0
}

// ScopeAnomaly is a single risk signal from a ScopeAnalyzer.
// Mirrors internal/credentials.ScopeAnomaly.
type ScopeAnomaly struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         AnomalyLevel           `protobuf:"varint,1,opt,name=level,proto3,enum=agentkms.plugin.v1.AnomalyLevel" json:"level,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScopeAnomaly) Reset() {
	*x = ScopeAnomaly{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScopeAnomaly) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScopeAnomaly) ProtoMessage() {}

func (x *ScopeAnomaly) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScopeAnomaly.ProtoReflect.Descriptor instead.
func (*ScopeAnomaly) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *ScopeAnomaly) GetLevel() AnomalyLevel {
	if x != nil {
		return x.Level
	}
	return AnomalyLevel_ANOMALY_LEVEL_UNSPECIFIED
}

func (x *ScopeAnomaly) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ScopeAnomaly) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// VendedCredential is the output of a CredentialVenderService.Vend call.
type VendedCredential struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// api_key holds the raw credential bytes (e.g. a bearer token or API key).
	// Handle with care — these bytes are secrets.
	ApiKey []byte `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	// uuid is the unique identifier for this vended credential instance,
	// used for audit correlation and revocation.
	Uuid string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// provider_token_hash is the SHA-256 hex digest of the upstream
	// provider token, for audit logging without storing the secret.
	ProviderTokenHash string `protobuf:"bytes,3,opt,name=provider_token_hash,json=providerTokenHash,proto3" json:"provider_token_hash,omitempty"`
	// expires_at is when the vended credential becomes invalid.
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VendedCredential) Reset() {
	*x = VendedCredential{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VendedCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VendedCredential) ProtoMessage() {}

func (x *VendedCredential) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VendedCredential.ProtoReflect.Descriptor instead.
func (*VendedCredential) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *VendedCredential) GetApiKey() []byte {
	if x != nil {
		return x.ApiKey
	}
	return nil
}

func (x *VendedCredential) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *VendedCredential) GetProviderTokenHash() string {
	if x != nil {
		return x.ProviderTokenHash
	}
	return ""
}

func (x *VendedCredential) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// PluginInfo describes a plugin implementation.
// Returned by any service's Info RPC or embedded in management messages.
type PluginInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kind is the scope Kind this plugin handles (e.g. "aws-sts").
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// api_version is the plugin API version this implementation targets
	// (e.g. "plugin.v1").
	ApiVersion string `protobuf:"bytes,2,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// name is a human-readable plugin name (e.g. "AWS STS Scope Plugin").
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// version is the plugin's own semantic version (e.g. "0.1.0").
	Version       string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *PluginInfo) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *PluginInfo) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// KindRequest is the input to any Kind RPC.  Intentionally empty.
type KindRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KindRequest) Reset() {
	*x = KindRequest{}
	mi := &file_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KindRequest) ProtoMessage() {}

func (x *KindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KindRequest.ProtoReflect.Descriptor instead.
func (*KindRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{5}
}

// KindResponse carries the Kind string the plugin handles.
type KindResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KindResponse) Reset() {
	*x = KindResponse{}
	mi := &file_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KindResponse) ProtoMessage() {}

func (x *KindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KindResponse.ProtoReflect.Descriptor instead.
func (*KindResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *KindResponse) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

// CapabilitiesRequest is the input to any Capabilities RPC.  Intentionally empty.
// The host sends this at startup after Kind() to negotiate supported features.
type CapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesRequest) Reset() {
	*x = CapabilitiesRequest{}
	mi := &file_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesRequest) ProtoMessage() {}

func (x *CapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*CapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{7}
}

// CapabilitiesResponse is returned by each service's Capabilities RPC.
// It lists the feature tokens the plugin supports and the API version it was
// built against.  The host stores this on the adapter struct for later policy
// decisions (e.g. require capability "revoke" before dispatching Revoke calls).
type CapabilitiesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// capabilities is the list of feature tokens this plugin service supports.
	// Examples: "health", "revoke", "audit", "streaming".
	// An empty list means no optional features beyond the baseline RPCs.
	Capabilities []string `protobuf:"bytes,1,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// api_version is the plugin API version this implementation targets
	// (numeric, e.g. 1). Used by the host for minimum-version compatibility
	// checks (host accepts any plugin where api_version >= host minimum).
	ApiVersion uint32 `protobuf:"varint,2,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// api_version_compat is a human-readable range string for display purposes
	// only (e.g. ">=1").  Not used for programmatic checks.
	ApiVersionCompat string `protobuf:"bytes,3,opt,name=api_version_compat,json=apiVersionCompat,proto3" json:"api_version_compat,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CapabilitiesResponse) Reset() {
	*x = CapabilitiesResponse{}
	mi := &file_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesResponse) ProtoMessage() {}

func (x *CapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*CapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *CapabilitiesResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *CapabilitiesResponse) GetApiVersion() uint32 {
	if x != nil {
		return x.ApiVersion
	}
	return 0
}

func (x *CapabilitiesResponse) GetApiVersionCompat() string {
	if x != nil {
		return x.ApiVersionCompat
	}
	return ""
}

// ValidateRequest is the input to ScopeValidatorService.Validate.
type ValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         *Scope                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *ValidateRequest) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

// ValidateResponse is the output of ScopeValidatorService.Validate.
// An empty error string means success.
type ValidateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// error is a human-readable error string.  Empty on success.
	Error         string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *ValidateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// NarrowRequest is the input to ScopeValidatorService.Narrow.
type NarrowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requested     *Scope                 `protobuf:"bytes,1,opt,name=requested,proto3" json:"requested,omitempty"`
	Bounds        *ScopeBounds           `protobuf:"bytes,2,opt,name=bounds,proto3" json:"bounds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NarrowRequest) Reset() {
	*x = NarrowRequest{}
	mi := &file_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NarrowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NarrowRequest) ProtoMessage() {}

func (x *NarrowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NarrowRequest.ProtoReflect.Descriptor instead.
func (*NarrowRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *NarrowRequest) GetRequested() *Scope {
	if x != nil {
		return x.Requested
	}
	return nil
}

func (x *NarrowRequest) GetBounds() *ScopeBounds {
	if x != nil {
		return x.Bounds
	}
	return nil
}

// NarrowResponse is the output of ScopeValidatorService.Narrow.
// On success, narrowed_scope contains the effective scope.
// On failure, error is non-empty and narrowed_scope is unset.
type NarrowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NarrowedScope *Scope                 `protobuf:"bytes,1,opt,name=narrowed_scope,json=narrowedScope,proto3" json:"narrowed_scope,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NarrowResponse) Reset() {
	*x = NarrowResponse{}
	mi := &file_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NarrowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NarrowResponse) ProtoMessage() {}

func (x *NarrowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NarrowResponse.ProtoReflect.Descriptor instead.
func (*NarrowResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *NarrowResponse) GetNarrowedScope() *Scope {
	if x != nil {
		return x.NarrowedScope
	}
	return nil
}

func (x *NarrowResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// AnalyzeRequest is the input to ScopeAnalyzerService.Analyze.
type AnalyzeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         *Scope                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeRequest) Reset() {
	*x = AnalyzeRequest{}
	mi := &file_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeRequest) ProtoMessage() {}

func (x *AnalyzeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *AnalyzeRequest) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

// AnalyzeResponse is the output of ScopeAnalyzerService.Analyze.
// An empty anomalies list means no risk signals were detected.
type AnalyzeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Anomalies     []*ScopeAnomaly        `protobuf:"bytes,1,rep,name=anomalies,proto3" json:"anomalies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeResponse) Reset() {
	*x = AnalyzeResponse{}
	mi := &file_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeResponse) ProtoMessage() {}

func (x *AnalyzeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *AnalyzeResponse) GetAnomalies() []*ScopeAnomaly {
	if x != nil {
		return x.Anomalies
	}
	return nil
}

// SerializeRequest is the input to ScopeSerializerService.Serialize.
type SerializeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         *Scope                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SerializeRequest) Reset() {
	*x = SerializeRequest{}
	mi := &file_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SerializeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerializeRequest) ProtoMessage() {}

func (x *SerializeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerializeRequest.ProtoReflect.Descriptor instead.
func (*SerializeRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *SerializeRequest) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

// SerializeResponse is the output of ScopeSerializerService.Serialize.
// provider_bytes contains the provider-native encoding of the scope
// (e.g. an AWS IAM policy document, a GitHub permissions object).
// Core never inspects or logs these bytes.
type SerializeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderBytes []byte                 `protobuf:"bytes,1,opt,name=provider_bytes,json=providerBytes,proto3" json:"provider_bytes,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SerializeResponse) Reset() {
	*x = SerializeResponse{}
	mi := &file_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SerializeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerializeResponse) ProtoMessage() {}

func (x *SerializeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerializeResponse.ProtoReflect.Descriptor instead.
func (*SerializeResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *SerializeResponse) GetProviderBytes() []byte {
	if x != nil {
		return x.ProviderBytes
	}
	return nil
}

func (x *SerializeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// VendRequest is the input to CredentialVenderService.Vend.
type VendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         *Scope                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VendRequest) Reset() {
	*x = VendRequest{}
	mi := &file_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VendRequest) ProtoMessage() {}

func (x *VendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VendRequest.ProtoReflect.Descriptor instead.
func (*VendRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *VendRequest) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

// VendResponse is the output of CredentialVenderService.Vend.
// On success, credential is populated.  On failure, error is non-empty.
type VendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credential    *VendedCredential      `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VendResponse) Reset() {
	*x = VendResponse{}
	mi := &file_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VendResponse) ProtoMessage() {}

func (x *VendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VendResponse.ProtoReflect.Descriptor instead.
func (*VendResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *VendResponse) GetCredential() *VendedCredential {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *VendResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\x12agentkms.plugin.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe1\x01\n" +
	"\x05Scope\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12/\n" +
	"\x06params\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06params\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\x127\n" +
	"\tissued_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\x81\x01\n" +
	"\vScopeBounds\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x126\n" +
	"\n" +
	"max_params\x18\x02 \x01(\v2\x17.google.protobuf.StructR\tmaxParams\x12&\n" +
	"\x0fmax_ttl_seconds\x18\x03 \x01(\x03R\rmaxTtlSeconds\"t\n" +
	"\fScopeAnomaly\x126\n" +
	"\x05level\x18\x01 \x01(\x0e2 .agentkms.plugin.v1.AnomalyLevelR\x05level\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xaa\x01\n" +
	"\x10VendedCredential\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\fR\x06apiKey\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12.\n" +
	"\x13provider_token_hash\x18\x03 \x01(\tR\x11providerTokenHash\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"o\n" +
	"\n" +
	"PluginInfo\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1f\n" +
	"\vapi_version\x18\x02 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"\r\n" +
	"\vKindRequest\"\"\n" +
	"\fKindResponse\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\"\x15\n" +
	"\x13CapabilitiesRequest\"\x89\x01\n" +
	"\x14CapabilitiesResponse\x12\"\n" +
	"\fcapabilities\x18\x01 \x03(\tR\fcapabilities\x12\x1f\n" +
	"\vapi_version\x18\x02 \x01(\rR\n" +
	"apiVersion\x12,\n" +
	"\x12api_version_compat\x18\x03 \x01(\tR\x10apiVersionCompat\"B\n" +
	"\x0fValidateRequest\x12/\n" +
	"\x05scope\x18\x01 \x01(\v2\x19.agentkms.plugin.v1.ScopeR\x05scope\"(\n" +
	"\x10ValidateResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\x81\x01\n" +
	"\rNarrowRequest\x127\n" +
	"\trequested\x18\x01 \x01(\v2\x19.agentkms.plugin.v1.ScopeR\trequested\x127\n" +
	"\x06bounds\x18\x02 \x01(\v2\x1f.agentkms.plugin.v1.ScopeBoundsR\x06bounds\"h\n" +
	"\x0eNarrowResponse\x12@\n" +
	"\x0enarrowed_scope\x18\x01 \x01(\v2\x19.agentkms.plugin.v1.ScopeR\rnarrowedScope\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"A\n" +
	"\x0eAnalyzeRequest\x12/\n" +
	"\x05scope\x18\x01 \x01(\v2\x19.agentkms.plugin.v1.ScopeR\x05scope\"Q\n" +
	"\x0fAnalyzeResponse\x12>\n" +
	"\tanomalies\x18\x01 \x03(\v2 .agentkms.plugin.v1.ScopeAnomalyR\tanomalies\"C\n" +
	"\x10SerializeRequest\x12/\n" +
	"\x05scope\x18\x01 \x01(\v2\x19.agentkms.plugin.v1.ScopeR\x05scope\"P\n" +
	"\x11SerializeResponse\x12%\n" +
	"\x0eprovider_bytes\x18\x01 \x01(\fR\rproviderBytes\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\">\n" +
	"\vVendRequest\x12/\n" +
	"\x05scope\x18\x01 \x01(\v2\x19.agentkms.plugin.v1.ScopeR\x05scope\"j\n" +
	"\fVendResponse\x12D\n" +
	"\n" +
	"credential\x18\x01 \x01(\v2$.agentkms.plugin.v1.VendedCredentialR\n" +
	"credential\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error*v\n" +
	"\fAnomalyLevel\x12\x1d\n" +
	"\x19ANOMALY_LEVEL_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ANOMALY_LEVEL_INFO\x10\x01\x12\x16\n" +
	"\x12ANOMALY_LEVEL_WARN\x10\x02\x12\x17\n" +
	"\x13ANOMALY_LEVEL_ALERT\x10\x032\xed\x02\n" +
	"\x15ScopeValidatorService\x12I\n" +
	"\x04Kind\x12\x1f.agentkms.plugin.v1.KindRequest\x1a .agentkms.plugin.v1.KindResponse\x12a\n" +
	"\fCapabilities\x12'.agentkms.plugin.v1.CapabilitiesRequest\x1a(.agentkms.plugin.v1.CapabilitiesResponse\x12U\n" +
	"\bValidate\x12#.agentkms.plugin.v1.ValidateRequest\x1a$.agentkms.plugin.v1.ValidateResponse\x12O\n" +
	"\x06Narrow\x12!.agentkms.plugin.v1.NarrowRequest\x1a\".agentkms.plugin.v1.NarrowResponse2\x98\x02\n" +
	"\x14ScopeAnalyzerService\x12I\n" +
	"\x04Kind\x12\x1f.agentkms.plugin.v1.KindRequest\x1a .agentkms.plugin.v1.KindResponse\x12a\n" +
	"\fCapabilities\x12'.agentkms.plugin.v1.CapabilitiesRequest\x1a(.agentkms.plugin.v1.CapabilitiesResponse\x12R\n" +
	"\aAnalyze\x12\".agentkms.plugin.v1.AnalyzeRequest\x1a#.agentkms.plugin.v1.AnalyzeResponse2\xa0\x02\n" +
	"\x16ScopeSerializerService\x12I\n" +
	"\x04Kind\x12\x1f.agentkms.plugin.v1.KindRequest\x1a .agentkms.plugin.v1.KindResponse\x12a\n" +
	"\fCapabilities\x12'.agentkms.plugin.v1.CapabilitiesRequest\x1a(.agentkms.plugin.v1.CapabilitiesResponse\x12X\n" +
	"\tSerialize\x12$.agentkms.plugin.v1.SerializeRequest\x1a%.agentkms.plugin.v1.SerializeResponse2\x92\x02\n" +
	"\x17CredentialVenderService\x12I\n" +
	"\x04Kind\x12\x1f.agentkms.plugin.v1.KindRequest\x1a .agentkms.plugin.v1.KindResponse\x12a\n" +
	"\fCapabilities\x12'.agentkms.plugin.v1.CapabilitiesRequest\x1a(.agentkms.plugin.v1.CapabilitiesResponse\x12I\n" +
	"\x04Vend\x12\x1f.agentkms.plugin.v1.VendRequest\x1a .agentkms.plugin.v1.VendResponseB5Z3github.com/agentkms/agentkms/api/plugin/v1;pluginv1b\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_plugin_proto_goTypes = []any{
	(AnomalyLevel)(0),             // 0: agentkms.plugin.v1.AnomalyLevel
	(*Scope)(nil),                 // 1: agentkms.plugin.v1.Scope
	(*ScopeBounds)(nil),           // 2: agentkms.plugin.v1.ScopeBounds
	(*ScopeAnomaly)(nil),          // 3: agentkms.plugin.v1.ScopeAnomaly
	(*VendedCredential)(nil),      // 4: agentkms.plugin.v1.VendedCredential
	(*PluginInfo)(nil),            // 5: agentkms.plugin.v1.PluginInfo
	(*KindRequest)(nil),           // 6: agentkms.plugin.v1.KindRequest
	(*KindResponse)(nil),          // 7: agentkms.plugin.v1.KindResponse
	(*CapabilitiesRequest)(nil),   // 8: agentkms.plugin.v1.CapabilitiesRequest
	(*CapabilitiesResponse)(nil),  // 9: agentkms.plugin.v1.CapabilitiesResponse
	(*ValidateRequest)(nil),       // 10: agentkms.plugin.v1.ValidateRequest
	(*ValidateResponse)(nil),      // 11: agentkms.plugin.v1.ValidateResponse
	(*NarrowRequest)(nil),         // 12: agentkms.plugin.v1.NarrowRequest
	(*NarrowResponse)(nil),        // 13: agentkms.plugin.v1.NarrowResponse
	(*AnalyzeRequest)(nil),        // 14: agentkms.plugin.v1.AnalyzeRequest
	(*AnalyzeResponse)(nil),       // 15: agentkms.plugin.v1.AnalyzeResponse
	(*SerializeRequest)(nil),      // 16: agentkms.plugin.v1.SerializeRequest
	(*SerializeResponse)(nil),     // 17: agentkms.plugin.v1.SerializeResponse
	(*VendRequest)(nil),           // 18: agentkms.plugin.v1.VendRequest
	(*VendResponse)(nil),          // 19: agentkms.plugin.v1.VendResponse
	(*structpb.Struct)(nil),       // 20: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 21: google.protobuf.Timestamp
}
var file_plugin_proto_depIdxs = []int32{
	20, // 0: agentkms.plugin.v1.Scope.params:type_name -> google.protobuf.Struct
	21, // 1: agentkms.plugin.v1.Scope.issued_at:type_name -> google.protobuf.Timestamp
	21, // 2: agentkms.plugin.v1.Scope.expires_at:type_name -> google.protobuf.Timestamp
	20, // 3: agentkms.plugin.v1.ScopeBounds.max_params:type_name -> google.protobuf.Struct
	0,  // 4: agentkms.plugin.v1.ScopeAnomaly.level:type_name -> agentkms.plugin.v1.AnomalyLevel
	21, // 5: agentkms.plugin.v1.VendedCredential.expires_at:type_name -> google.protobuf.Timestamp
	1,  // 6: agentkms.plugin.v1.ValidateRequest.scope:type_name -> agentkms.plugin.v1.Scope
	1,  // 7: agentkms.plugin.v1.NarrowRequest.requested:type_name -> agentkms.plugin.v1.Scope
	2,  // 8: agentkms.plugin.v1.NarrowRequest.bounds:type_name -> agentkms.plugin.v1.ScopeBounds
	1,  // 9: agentkms.plugin.v1.NarrowResponse.narrowed_scope:type_name -> agentkms.plugin.v1.Scope
	1,  // 10: agentkms.plugin.v1.AnalyzeRequest.scope:type_name -> agentkms.plugin.v1.Scope
	3,  // 11: agentkms.plugin.v1.AnalyzeResponse.anomalies:type_name -> agentkms.plugin.v1.ScopeAnomaly
	1,  // 12: agentkms.plugin.v1.SerializeRequest.scope:type_name -> agentkms.plugin.v1.Scope
	1,  // 13: agentkms.plugin.v1.VendRequest.scope:type_name -> agentkms.plugin.v1.Scope
	4,  // 14: agentkms.plugin.v1.VendResponse.credential:type_name -> agentkms.plugin.v1.VendedCredential
	6,  // 15: agentkms.plugin.v1.ScopeValidatorService.Kind:input_type -> agentkms.plugin.v1.KindRequest
	8,  // 16: agentkms.plugin.v1.ScopeValidatorService.Capabilities:input_type -> agentkms.plugin.v1.CapabilitiesRequest
	10, // 17: agentkms.plugin.v1.ScopeValidatorService.Validate:input_type -> agentkms.plugin.v1.ValidateRequest
	12, // 18: agentkms.plugin.v1.ScopeValidatorService.Narrow:input_type -> agentkms.plugin.v1.NarrowRequest
	6,  // 19: agentkms.plugin.v1.ScopeAnalyzerService.Kind:input_type -> agentkms.plugin.v1.KindRequest
	8,  // 20: agentkms.plugin.v1.ScopeAnalyzerService.Capabilities:input_type -> agentkms.plugin.v1.CapabilitiesRequest
	14, // 21: agentkms.plugin.v1.ScopeAnalyzerService.Analyze:input_type -> agentkms.plugin.v1.AnalyzeRequest
	6,  // 22: agentkms.plugin.v1.ScopeSerializerService.Kind:input_type -> agentkms.plugin.v1.KindRequest
	8,  // 23: agentkms.plugin.v1.ScopeSerializerService.Capabilities:input_type -> agentkms.plugin.v1.CapabilitiesRequest
	16, // 24: agentkms.plugin.v1.ScopeSerializerService.Serialize:input_type -> agentkms.plugin.v1.SerializeRequest
	6,  // 25: agentkms.plugin.v1.CredentialVenderService.Kind:input_type -> agentkms.plugin.v1.KindRequest
	8,  // 26: agentkms.plugin.v1.CredentialVenderService.Capabilities:input_type -> agentkms.plugin.v1.CapabilitiesRequest
	18, // 27: agentkms.plugin.v1.CredentialVenderService.Vend:input_type -> agentkms.plugin.v1.VendRequest
	7,  // 28: agentkms.plugin.v1.ScopeValidatorService.Kind:output_type -> agentkms.plugin.v1.KindResponse
	9,  // 29: agentkms.plugin.v1.ScopeValidatorService.Capabilities:output_type -> agentkms.plugin.v1.CapabilitiesResponse
	11, // 30: agentkms.plugin.v1.ScopeValidatorService.Validate:output_type -> agentkms.plugin.v1.ValidateResponse
	13, // 31: agentkms.plugin.v1.ScopeValidatorService.Narrow:output_type -> agentkms.plugin.v1.NarrowResponse
	7,  // 32: agentkms.plugin.v1.ScopeAnalyzerService.Kind:output_type -> agentkms.plugin.v1.KindResponse
	9,  // 33: agentkms.plugin.v1.ScopeAnalyzerService.Capabilities:output_type -> agentkms.plugin.v1.CapabilitiesResponse
	15, // 34: agentkms.plugin.v1.ScopeAnalyzerService.Analyze:output_type -> agentkms.plugin.v1.AnalyzeResponse
	7,  // 35: agentkms.plugin.v1.ScopeSerializerService.Kind:output_type -> agentkms.plugin.v1.KindResponse
	9,  // 36: agentkms.plugin.v1.ScopeSerializerService.Capabilities:output_type -> agentkms.plugin.v1.CapabilitiesResponse
	17, // 37: agentkms.plugin.v1.ScopeSerializerService.Serialize:output_type -> agentkms.plugin.v1.SerializeResponse
	7,  // 38: agentkms.plugin.v1.CredentialVenderService.Kind:output_type -> agentkms.plugin.v1.KindResponse
	9,  // 39: agentkms.plugin.v1.CredentialVenderService.Capabilities:output_type -> agentkms.plugin.v1.CapabilitiesResponse
	19, // 40: agentkms.plugin.v1.CredentialVenderService.Vend:output_type -> agentkms.plugin.v1.VendResponse
	28, // [28:41] is the sub-list for method output_type
	15, // [15:28] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		EnumInfos:         file_plugin_proto_enumTypes,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
