package audit

import (
	"crypto/rand"
	"fmt"
	"io"
	"regexp"
	"strings"
	"time"
)

// hexKeyPattern matches 64 or more consecutive hexadecimal characters.
// 64 hex chars = 32 bytes = the minimum size for key material that
// AgentKMS handles: AES-256 keys, SHA-256 digests, Ed25519 seeds, and
// ECDSA P-256 scalars are all exactly 32 bytes in raw form.
//
// The pattern has no anchors so it matches anywhere inside a string —
// a 64-char hex run embedded in a longer message is still flagged.
var hexKeyPattern = regexp.MustCompile(`[0-9a-fA-F]{64,}`)

// ── Operation constants ───────────────────────────────────────────────────────

// Operation values for AuditEvent.Operation.  Use these constants everywhere;
// free-form strings make dashboards and alerts fragile.
const (
	OperationSign           = "sign"
	OperationEncrypt        = "encrypt"
	OperationDecrypt        = "decrypt"
	OperationCredentialVend = "credential_vend"
	OperationCredentialUse  = "credential_use"
	OperationCredRefresh    = "credential_refresh"
	OperationAuth           = "auth"
	OperationAuthRefresh    = "auth_refresh"
	OperationRevoke         = "revoke"
	OperationListKeys       = "list_keys"
	OperationRotateKey      = "rotate_key"
	OperationBlockedRead    = "blocked_read"
	OperationPanicRecovery  = "panic_recovery"
	OperationKeyCreate      = "key_create"
)

// ── Outcome constants ─────────────────────────────────────────────────────────

// Outcome values for AuditEvent.Outcome.
const (
	OutcomeSuccess = "success"
	OutcomeDenied  = "denied"
	OutcomeError   = "error"
)

// ── AuditEvent ────────────────────────────────────────────────────────────────

// AuditEvent is the canonical, immutable record written for every operation
// performed by AgentKMS.  It is the unit of compliance evidence.
//
// SECURITY INVARIANTS — every field must respect these rules:
//
//  1. PayloadHash contains a SHA-256 hash of the input payload, formatted as
//     "sha256:<hex>".  It MUST NOT contain the raw payload.
//
//  2. KeyID contains a key identifier string.  It MUST NOT contain key
//     material (private key bytes, symmetric key bytes, or LLM API keys).
//
//  3. No field of AuditEvent may contain raw private key material, plaintext
//     data, or LLM provider API keys.  If you are adding a new field, ask:
//     "could this field accidentally carry sensitive material?" — if yes,
//     redesign the field.
//
// All fields use `json` struct tags so the event serialises consistently
// regardless of which audit sink receives it.
type AuditEvent struct {
	// EventID is a unique identifier for this event.  Format: UUID v4.
	// Generated by NewEventID(); callers should not set this manually.
	EventID string `json:"event_id"`

	// Timestamp is when the event was created (UTC, RFC 3339 nanosecond
	// precision).
	Timestamp time.Time `json:"timestamp"`

	// CallerID identifies the calling entity, extracted from the mTLS
	// certificate's Common Name or workload identity.
	// Example: "bert@platform-team", "ci-runner@payments-team".
	CallerID string `json:"caller_id"`

	// TeamID is the team that owns the calling identity (cert O field).
	TeamID string `json:"team_id"`

	// AgentSession is the per-Pi-session identifier.  Correlates all
	// operations within a single Pi session in the audit trail.
	// Empty for non-session operations (e.g. service-to-service calls).
	AgentSession string `json:"agent_session,omitempty"`

	// Operation is the action being audited.  Use the Operation* constants.
	Operation string `json:"operation"`

	// KeyID is the identifier of the key involved in this operation.
	// Example: "payments/signing-key".  NEVER contains key material.
	KeyID string `json:"key_id,omitempty"`

	// KeyVersion is the version number of the key used.  Included in the
	// audit trail so that the exact key version can be correlated with a
	// specific operation.
	KeyVersion int `json:"key_version,omitempty"`

	// PayloadHash is "sha256:<hex-encoded SHA-256 of the input payload>".
	// NEVER the payload itself.  Omitted for operations that have no payload
	// (e.g. ListKeys, auth).
	PayloadHash string `json:"payload_hash,omitempty"`

	// Algorithm is the cryptographic algorithm used, e.g. "ES256",
	// "AES256GCM".  Omitted for non-crypto operations.
	Algorithm string `json:"algorithm,omitempty"`

	// Outcome is the result of the operation.  Use the Outcome* constants.
	Outcome string `json:"outcome"`

	// DenyReason explains why an operation was denied.  Empty on success or
	// non-denial errors.
	//
	// SECURITY CONSTRAINT: DenyReason MUST contain only human-readable policy
	// explanation text.  It MUST NOT contain:
	//   - Key material (private key bytes, AES key bytes, LLM API keys)
	//   - Stack traces (use structured logging for debug context)
	//   - Raw payloads or decrypted data
	//   - PEM-encoded key blocks
	//
	// Safe examples: "policy: identity not permitted for key namespace",
	//   "rate limit exceeded", "token expired".
	// Unsafe: fmt.Sprintf("key %x denied", keyBytes) — never do this.
	DenyReason string `json:"deny_reason,omitempty"`

	// SourceIP is the caller's remote IP address (without port).
	SourceIP string `json:"source_ip,omitempty"`

	// UserAgent is the caller's User-Agent header value.
	UserAgent string `json:"user_agent,omitempty"`

	// ComplianceTags lists the compliance frameworks relevant to this event.
	// Example: ["pci-dss", "soc2", "iso27001"].
	// Used by compliance dashboards to filter events by framework.
	ComplianceTags []string `json:"compliance_tags,omitempty"`

	// Environment identifies the deployment tier.
	// Values: "production", "staging", "dev".
	Environment string `json:"environment,omitempty"`

	// ErrorDetail captures technical error information for troubleshooting.
	// Present only when Outcome is OutcomeError.
	// SECURITY: Must not contain key material, plaintext, or credentials.
	ErrorDetail string `json:"error_detail,omitempty"`
}

// ── EventID generation ────────────────────────────────────────────────────────

// NewEventID returns a new UUID v4 string for use as AuditEvent.EventID.
// It reads from crypto/rand; returns an error only if the OS entropy source
// is exhausted (essentially impossible in practice).
//
// Format: xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx  (RFC 4122 §4.4)
func NewEventID() (string, error) {
	var b [16]byte
	if _, err := io.ReadFull(rand.Reader, b[:]); err != nil {
		return "", fmt.Errorf("audit: generating event ID: %w", err)
	}
	// Set version (4) and variant (RFC 4122) bits.
	b[6] = (b[6] & 0x0f) | 0x40
	b[8] = (b[8] & 0x3f) | 0x80
	return fmt.Sprintf("%08x-%04x-%04x-%04x-%012x",
		b[0:4], b[4:6], b[6:8], b[8:10], b[10:16]), nil
}

// ── Validation ───────────────────────────────────────────────────────────────

// Validate performs a runtime security check verifying that free-text fields
// in the AuditEvent do not contain patterns associated with key material.
//
// Fields checked:
//   - DenyReason, ErrorDetail, CallerID, UserAgent, KeyID:
//     must not contain PEM block delimiters ("-----BEGIN" /
//     "-----END") or a hex-encoded sequence of ≥ 32 bytes (64 hex chars).
//
// Why fail closed: if any free-text field contains a PEM-encoded private key
// or a 32-byte hex blob, writing it to any audit sink (ELK, Splunk, CloudWatch)
// constitutes a key-material leak — a catastrophic security violation.
// A missed audit event is recoverable; a key leak is not.
//
// Callers (Auditor implementations) MUST call Validate before writing.
// MultiAuditor.Log enforces this automatically.
//
// F-09.
func (e AuditEvent) Validate() error {
	for _, fc := range []struct {
		name  string
		value string
	}{
		{"DenyReason", e.DenyReason},
		{"ErrorDetail", e.ErrorDetail},
		{"CallerID", e.CallerID},
		{"UserAgent", e.UserAgent},
		{"KeyID", e.KeyID},
	} {
		if err := checkForKeyMaterial(fc.name, fc.value); err != nil {
			return fmt.Errorf("audit: AuditEvent.Validate: %w", err)
		}
	}
	return nil
}

// checkForKeyMaterial checks a single free-text field for key material
// patterns. It is intentionally conservative: a false positive (blocking
// a deny reason that happens to contain a long hex run) is far preferable
// to a false negative (silently writing a private key to an audit sink).
func checkForKeyMaterial(field, value string) error {
	if value == "" {
		return nil
	}
	// PEM block delimiters — the canonical markers for encoded key material.
	if strings.Contains(value, "-----BEGIN") || strings.Contains(value, "-----END") {
		return fmt.Errorf(
			"field %q contains a PEM block delimiter — key material must not appear in audit events",
			field,
		)
	}
	// Hex blob of ≥ 32 bytes — matches raw key material formatted with
	// fmt.Sprintf("%x", keyBytes) or hex.EncodeToString(keyBytes).
	if hexKeyPattern.MatchString(value) {
		return fmt.Errorf(
			"field %q contains a hex sequence of ≥ 32 bytes — possible key material",
			field,
		)
	}
	return nil
}

// ── Event construction ────────────────────────────────────────────────────────

// New returns a new AuditEvent with EventID and Timestamp pre-populated.
// Callers should fill in the remaining fields before passing to Auditor.Log.
//
// Usage:
//
//	ev, err := audit.New()
//	if err != nil { ... }
//	ev.CallerID   = identity.CallerID
//	ev.Operation  = audit.OperationSign
//	ev.Outcome    = audit.OutcomeSuccess
//	auditor.Log(ctx, ev)
func New() (AuditEvent, error) {
	id, err := NewEventID()
	if err != nil {
		return AuditEvent{}, err
	}
	return AuditEvent{
		EventID:   id,
		Timestamp: time.Now().UTC(),
	}, nil
}
