"""
AgentKMS Reference Plugin — Honeytoken Scope Validator (Python)

Demonstrates how to write an AgentKMS plugin in Python using the
gRPC plugin API. This plugin validates "honeytoken" credential scopes:
fake credentials planted as tripwires used for leak detection.

Implements: ScopeValidatorService (Kind = "honeytoken")
  - Kind     → returns "honeytoken"
  - Validate → checks that params has "name" and "purpose" (non-empty strings)
  - Narrow   → passes through unchanged (honeytokens are not policy-narrowed)

Usage:
    # 1. Generate gRPC stubs (once)
    bash generate.sh

    # 2. Run the plugin
    python plugin.py

The plugin speaks the hashicorp/go-plugin handshake protocol:
  - Reads PLUGIN_MAGIC_COOKIE from env (expected value: agentkms_plugin_v1)
  - Prints the connection line to stdout: 1|1|tcp|127.0.0.1:{port}|grpc
  - Serves gRPC on that port until the process is terminated

AgentKMS discovers plugins by launching their binary and reading the
first line of stdout. The plugin host (Go side) will then connect via
gRPC on the advertised address.
"""

from __future__ import annotations

import os
import socket
import sys
from concurrent import futures
from typing import Any

# ── Constants ──────────────────────────────────────────────────────────────────

KIND: str = "honeytoken"

# The magic cookie AgentKMS sets before launching a plugin binary.
# Mismatch → refuse to start (safety check against accidental direct invocation).
PLUGIN_MAGIC_COOKIE_KEY: str = "PLUGIN_MAGIC_COOKIE"
PLUGIN_MAGIC_COOKIE_VAL: str = "agentkms_plugin_v1"

# hashicorp/go-plugin protocol version constants.
_CORE_PROTOCOL_VERSION: int = 1
_APP_PROTOCOL_VERSION: int = 1
_NETWORK: str = "tcp"
_PROTOCOL: str = "grpc"


# ── Pure validation logic (no gRPC dependency) ─────────────────────────────────
#
# These functions are the real business logic. They are kept separate from the
# gRPC wiring so they can be imported and tested without any gRPC infrastructure.


def kind() -> str:
    """Return the scope Kind this plugin handles."""
    return KIND


def validate_params(params: dict[str, Any]) -> str:
    """
    Validate honeytoken scope params.

    A honeytoken scope is valid when params contains:
      - "name"    — a non-empty string identifying the honeytoken
      - "purpose" — a non-empty string describing why the token was planted

    Returns an empty string on success, or a human-readable error string.

    Args:
        params: The scope params dict (from Scope.params / google.protobuf.Struct).

    Returns:
        "" on success, non-empty error message on failure.
    """
    name = params.get("name")
    if not isinstance(name, str) or not name.strip():
        return 'params["name"] is required and must be a non-empty string'

    purpose = params.get("purpose")
    if not isinstance(purpose, str) or not purpose.strip():
        return 'params["purpose"] is required and must be a non-empty string'

    return ""


def narrow_scope(
    requested_params: dict[str, Any],
    max_params: dict[str, Any],  # noqa: ARG001  (unused — honeytokens pass through)
) -> tuple[dict[str, Any], str]:
    """
    Narrow a requested honeytoken scope against policy bounds.

    Honeytokens are self-contained tripwires; there is no meaningful
    parameter to restrict. This implementation passes the requested
    scope through unchanged.

    Args:
        requested_params: The params from the requested Scope.
        max_params: The maximum allowed params from ScopeBounds (ignored).

    Returns:
        A (narrowed_params, error) tuple.
        error is "" on success, non-empty on failure.
    """
    # Pass through — no narrowing semantics for honeytokens.
    return requested_params, ""


# ── gRPC service implementation ────────────────────────────────────────────────
#
# This section wires the pure logic above into the gRPC servicer generated by
# generate.sh. It is intentionally isolated so the file is still importable
# (for testing) even before stubs are generated.

def _build_servicer():  # noqa: ANN202
    """
    Build and return the gRPC servicer class.

    Deferred import allows the module to be imported for testing even when
    plugin_pb2 / plugin_pb2_grpc have not been generated yet.

    Raises:
        ImportError: if generate.sh has not been run.
    """
    try:
        import plugin_pb2 as pb2  # type: ignore[import]
        import plugin_pb2_grpc as pb2_grpc  # type: ignore[import]
    except ModuleNotFoundError as exc:
        raise ImportError(
            "gRPC stubs not found. Run `bash generate.sh` first."
        ) from exc

    class HoneytokenValidatorServicer(pb2_grpc.ScopeValidatorServiceServicer):
        """gRPC servicer: routes incoming RPCs to pure-Python logic above."""

        def Kind(
            self,
            request: pb2.KindRequest,  # noqa: ARG002
            context: Any,  # grpc.ServicerContext — typed as Any to avoid import
        ) -> pb2.KindResponse:
            """Return the scope Kind this plugin handles."""
            return pb2.KindResponse(kind=kind())

        def Validate(
            self,
            request: pb2.ValidateRequest,
            context: Any,  # grpc.ServicerContext — typed as Any to avoid import
        ) -> pb2.ValidateResponse:
            """Validate structural correctness of the honeytoken scope."""
            # google.protobuf.Struct → plain Python dict via MessageToDict-style
            # access: pb2.Struct fields are accessed through .fields, but the
            # grpc_tools-generated Struct already exposes a dict-like view via
            # the standard google.protobuf.struct_pb2 helpers.
            params = _struct_to_dict(request.scope.params)
            error = validate_params(params)
            return pb2.ValidateResponse(error=error)

        def Narrow(
            self,
            request: pb2.NarrowRequest,
            context: Any,  # grpc.ServicerContext — typed as Any to avoid import
        ) -> pb2.NarrowResponse:
            """Intersect requested scope with policy bounds."""
            requested_params = _struct_to_dict(request.requested.params)
            max_params = _struct_to_dict(request.bounds.max_params)

            narrowed_params, error = narrow_scope(requested_params, max_params)
            if error:
                return pb2.NarrowResponse(error=error)

            # Rebuild the narrowed Scope, preserving all non-params fields.
            narrowed_scope = pb2.Scope(
                kind=request.requested.kind,
                params=_dict_to_struct(narrowed_params),
                ttl_seconds=request.requested.ttl_seconds,
                issued_at=request.requested.issued_at,
                expires_at=request.requested.expires_at,
            )
            return pb2.NarrowResponse(narrowed_scope=narrowed_scope, error="")

    return HoneytokenValidatorServicer, pb2_grpc


# ── protobuf Struct helpers ────────────────────────────────────────────────────


def _struct_to_dict(struct_msg: Any) -> dict[str, Any]:
    """
    Convert a google.protobuf.Struct message to a plain Python dict.

    Uses the standard MessageToDict approach via the well-known type's
    built-in conversion rather than importing google.protobuf.json_format
    to keep dependencies minimal.
    """
    from google.protobuf import json_format  # type: ignore[import]
    return json_format.MessageToDict(struct_msg)


def _dict_to_struct(d: dict[str, Any]) -> Any:
    """Convert a plain Python dict to a google.protobuf.Struct message."""
    from google.protobuf import json_format, struct_pb2  # type: ignore[import]
    struct_msg = struct_pb2.Struct()
    json_format.ParseDict(d, struct_msg)
    return struct_msg


# ── go-plugin handshake ────────────────────────────────────────────────────────


def _check_magic_cookie() -> None:
    """
    Verify the magic cookie environment variable.

    hashicorp/go-plugin sets this before launching a plugin subprocess.
    A mismatch means the binary was invoked directly — print a helpful
    error and exit rather than silently misbehaving.
    """
    actual = os.environ.get(PLUGIN_MAGIC_COOKIE_KEY, "")
    if actual != PLUGIN_MAGIC_COOKIE_VAL:
        print(
            f"This binary is an AgentKMS plugin and should not be run directly.\n"
            f"Set {PLUGIN_MAGIC_COOKIE_KEY}={PLUGIN_MAGIC_COOKIE_VAL} "
            f"or let AgentKMS launch it.",
            file=sys.stderr,
        )
        sys.exit(1)


def _find_free_port() -> int:
    """Bind to port 0 and return the OS-assigned port number."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(("127.0.0.1", 0))
        return s.getsockname()[1]


def _announce(port: int) -> None:
    """
    Print the go-plugin connection line to stdout.

    Format (per hashicorp/go-plugin v1 protocol):
        CORE_PROTOCOL|APP_PROTOCOL|NETWORK|ADDRESS|PROTOCOL

    Example:
        1|1|tcp|127.0.0.1:50051|grpc

    The host reads this line immediately after spawning the subprocess
    and connects to the advertised address.
    """
    line = f"{_CORE_PROTOCOL_VERSION}|{_APP_PROTOCOL_VERSION}|{_NETWORK}|127.0.0.1:{port}|{_PROTOCOL}"
    # Flush immediately — the host reads this synchronously.
    print(line, flush=True)


# ── Server entrypoint ──────────────────────────────────────────────────────────


def serve() -> None:
    """
    Start the gRPC server and speak the go-plugin handshake protocol.

    Steps:
      1. Verify the magic cookie (safety check).
      2. Build the gRPC servicer from generated stubs.
      3. Find a free local port and bind the gRPC server.
      4. Announce the port to stdout (go-plugin reads this).
      5. Block until the process is killed by the plugin host.
    """
    import grpc  # noqa: PLC0415 — deferred so pure logic is importable without grpc

    _check_magic_cookie()

    HoneytokenValidatorServicer, pb2_grpc = _build_servicer()

    port = _find_free_port()
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=4))
    pb2_grpc.add_ScopeValidatorServiceServicer_to_server(
        HoneytokenValidatorServicer(), server
    )
    server.add_insecure_port(f"127.0.0.1:{port}")
    server.start()

    _announce(port)

    # Block forever — the plugin host owns the lifecycle.
    server.wait_for_termination()


if __name__ == "__main__":
    serve()
