// Package keystore provides hardware-backed private key storage for AgentKMS.
//
// Private keys generated by this package NEVER touch the filesystem as
// plaintext.  Depending on the platform, keys are protected by:
//
//   - macOS: Apple Secure Enclave (M1/M2/M3/T2) via Security.framework.
//     The key is generated inside the SEP coprocessor and is bound to the
//     device.  It is never extractable, even with physical access.
//
//   - Linux + YubiKey: PKCS#11 via the PIV applet.  The key is generated on
//     the YubiKey and requires a PIN to sign.  Physical possession of the
//     token is required for every signing operation.
//
//   - Fallback (any platform): The private key is generated in-process and
//     immediately encrypted with AES-256-GCM using a key derived from a
//     passphrase via Argon2id (the PHC competition winner, used by 1Password).
//     The encrypted blob is stored at ~/.agentkms/client.key.enc.
//     An attacker with the encrypted blob still cannot sign without the
//     passphrase.  An attacker with RAM access cannot extract the key because
//     it is only decrypted for the duration of a TLS handshake.
//
// Usage:
//
//	ks, err := keystore.Open(keystore.Config{Dir: "~/.agentkms"})
//	signer, err := ks.Signer()
//	// signer implements crypto.Signer — pass it to tls.Certificate.PrivateKey
package keystore

import (
	"crypto"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/x509"
	"encoding/pem"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
)

// Backend identifies the key protection mechanism in use.
type Backend string

const (
	BackendSecureEnclave Backend = "secure_enclave" // macOS SEP
	BackendPKCS11        Backend = "pkcs11"         // YubiKey / HSM
	BackendEncryptedFile Backend = "encrypted_file" // Argon2id + AES-256-GCM
)

// Config holds configuration for opening a KeyStore.
type Config struct {
	// Dir is the directory where key material (or encrypted blobs) is stored.
	// Defaults to ~/.agentkms if empty.
	Dir string

	// Passphrase is used by the EncryptedFile backend.
	// If empty, the user is prompted interactively.
	Passphrase string

	// PKCS11Lib is the path to the PKCS#11 shared library (e.g. libykcs11.so).
	// Only used by the PKCS11 backend.
	PKCS11Lib string

	// PKCS11Slot is the PKCS#11 slot number.  Defaults to 0.
	PKCS11Slot uint

	// KeyLabel is the label used when creating/finding the key in the hardware store.
	KeyLabel string

	// ForceBackend overrides auto-detection.  Empty = auto.
	ForceBackend Backend
}

// KeyStore holds a reference to a private key (or the hardware token that holds it).
type KeyStore interface {
	// Backend reports which protection mechanism is in use.
	Backend() Backend

	// Signer returns a crypto.Signer backed by the hardware or encrypted file.
	// On Secure Enclave and PKCS#11 backends, every call to Sign() is
	// hardware-delegated and never exposes key material in process memory.
	Signer() (crypto.Signer, error)

	// PublicKey returns the public key corresponding to the stored private key.
	PublicKey() (crypto.PublicKey, error)

	// Close releases any held hardware resources (PKCS#11 sessions, etc).
	Close() error
}

// Open returns a KeyStore using the best available backend for this platform.
// If no hardware is present, it falls back to the encrypted file backend.
//
// If a key has not yet been generated, Open will return ErrKeyNotFound.
// Call Generate() to create and persist a new key.
func Open(cfg Config) (KeyStore, error) {
	if cfg.Dir == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			return nil, fmt.Errorf("keystore: resolve home dir: %w", err)
		}
		cfg.Dir = filepath.Join(home, ".agentkms")
	}
	if cfg.KeyLabel == "" {
		cfg.KeyLabel = "agentkms-identity"
	}

	backend := cfg.ForceBackend
	if backend == "" {
		backend = detectBackend(cfg)
	}

	switch backend {
	case BackendSecureEnclave:
		return openSecureEnclave(cfg)
	case BackendPKCS11:
		return openPKCS11(cfg)
	default:
		return openEncryptedFile(cfg)
	}
}

// Generate creates a new P-256 private key protected by the best available
// backend and persists it.  Returns an error if a key already exists.
func Generate(cfg Config) (KeyStore, error) {
	if cfg.Dir == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			return nil, fmt.Errorf("keystore: resolve home dir: %w", err)
		}
		cfg.Dir = filepath.Join(home, ".agentkms")
	}
	if cfg.KeyLabel == "" {
		cfg.KeyLabel = "agentkms-identity"
	}
	if err := os.MkdirAll(cfg.Dir, 0700); err != nil {
		return nil, fmt.Errorf("keystore: create dir: %w", err)
	}

	backend := cfg.ForceBackend
	if backend == "" {
		backend = detectBackend(cfg)
	}

	switch backend {
	case BackendSecureEnclave:
		return generateSecureEnclave(cfg)
	case BackendPKCS11:
		return generatePKCS11(cfg)
	default:
		return generateEncryptedFile(cfg)
	}
}

// ErrKeyNotFound is returned when no key has been generated for this device.
var ErrKeyNotFound = errors.New("keystore: no key found — run agentkms enroll")

// detectBackend returns the best available backend for the current platform.
func detectBackend(cfg Config) Backend {
	if cfg.PKCS11Lib != "" {
		if _, err := os.Stat(cfg.PKCS11Lib); err == nil {
			return BackendPKCS11
		}
	}
	if runtime.GOOS == "darwin" && supportsSecureEnclave() {
		return BackendSecureEnclave
	}
	return BackendEncryptedFile
}

// GenerateEphemeralKeyPair generates a P-256 key pair in-process and returns
// PEM-encoded cert/key bytes.  Used by enrollment to generate the CSR key
// before hardware binding is complete.  The returned key must be discarded
// immediately after the CSR is signed.
func GenerateEphemeralKeyPair() (privKeyPEM, pubKeyPEM []byte, err error) {
	priv, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return nil, nil, fmt.Errorf("keystore: generate ephemeral key: %w", err)
	}
	privDER, err := x509.MarshalECPrivateKey(priv)
	if err != nil {
		return nil, nil, fmt.Errorf("keystore: marshal ephemeral key: %w", err)
	}
	pubDER, err := x509.MarshalPKIXPublicKey(&priv.PublicKey)
	if err != nil {
		return nil, nil, fmt.Errorf("keystore: marshal ephemeral pub: %w", err)
	}
	privKeyPEM = pem.EncodeToMemory(&pem.Block{Type: "EC PRIVATE KEY", Bytes: privDER})
	pubKeyPEM = pem.EncodeToMemory(&pem.Block{Type: "PUBLIC KEY", Bytes: pubDER})
	return privKeyPEM, pubKeyPEM, nil
}
